### ISSUE TITLE
A new package with Packrat doesn't have documentation in the build configure

### ISSUE THREAD

**Issue by znmeb** [rstudio/packrat#150]
1. Create a new project - R package build tools, Packrat enabled
2. Go to the 'Configure package build tools' menu. 'Generate documentation with Roxygen' isn't there.
3. Turn off Packrat.
4. Now the 'Generate documentation' part is there.
5. You can now turn Packrat back on and the documentation setting is still there.

RStudio is  0.98.1062, Packrat is  packrat   0.4.1-1 from CRAN - will try later with packrat from Github.

**Comment by gmonaie** [comment]
if you install `devtools` inside the packrat package you just created the options will show up without having to run the workaround above. `devtools` imports `roxygen2` and will install it as well.

`install.packages('devtools')`
