### ISSUE TITLE
Bootstrapping from a script

### ISSUE THREAD

**Issue by krlmlr** [rstudio/packrat#158]
Currently I use `R --vanilla --interactive -f .Rprofile < /dev/null` to bootstrap a Packrat project from a script. Is there a better way?

**Comment by benmarwick** [comment]
@krlmlr I see you [mention](https://github.com/rstudio/packrat/issues/158#issuecomment-59566668) using packrat with continuous integration, which might mean you have solved the problem I've asked  elsewhere about using packrat when building R packages on Travis ([1](https://github.com/rstudio/packrat/issues/330), [2](https://github.com/travis-ci/travis-ci/issues/6504)). Would it be possible for you to share the code that enables you to use packrat with your CI service?
