### ISSUE TITLE
biocLite() finds old version of DBI

### ISSUE THREAD

**Issue by gnomics** [rstudio/packrat#182]
I am trying to setup a packrat project that includes Bioconductor.  However, it appears that biocLite is still detecting an older system-wide installation of DBI.  Perplexingly, I'm not able to library("DBI") in a new packrat directory if I don't first run biocLite().  Any ideas why this would be the case?

Setup:

```
packrat::init()
source("http://bioconductor.org/biocLite.R")
biocLite()
```

Error message:
```
** testing if installed package can be loaded
Error : package ‘DBI’ 0.2-7 was found, but >= 0.3.1 is required by ‘RSQLite’
```

Confirmation that packrat contains DBI 0.3.1:
```
> library("DBI")
> sessionInfo()
R version 3.0.1 (2013-05-16)
Platform: x86_64-pc-linux-gnu (64-bit)

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=C                 LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] DBI_0.3.1

loaded via a namespace (and not attached):
[1] packrat_0.4.2-9 tools_3.0.1    
```

and

```
$ head packrat/lib/x86_64-pc-linux-gnu/3.0.1/DBI/DESCRIPTION 
Package: DBI
Version: 0.3.1
```

.libPaths()
```
[1] "/home/gnomics/test/packrat/lib/x86_64-pc-linux-gnu/3.0.1"
[2] "/home/gnomics/test/packrat/lib-ext"                      
[3] "/usr/lib/R/library" 
```

**Comment by gnomics** [comment]
It appears that when biocLite() reaches the "testing if installed package can be loaded" stage, it sources /etc/R/Rprofile.site where I have .Library.site set to a custom system-wide folder (if I comment out that line, biocLite() no longer finds the older version of DBI). Is this the expected behavior?

**Comment by kevinushey** [comment]
I'm a bit confused -- is `biocLite()` really modifying the `.libPaths()` out from under you? What does the call stack look like if you do `debug(source); biocLite()` and then execute `sys.calls()` once the debugger is activated?

**Comment by gnomics** [comment]
Sorry, but I've never used `debug()` or `sys.calls()` before.  When I run `debug(source); biocLite()` it attempts to upgrade and fails at the DBI >=0.3.1 dependency.  If I then run `sys.calls()` it returns `NULL`.

In this particular case, `biocLite()` downloads the source for RSQLite, compiles, installs to `/home/gnomics/test/packrat/lib/x86_64-pc-linux-gnu/3.0.1/RSQLite/libs`, builds the package, and then tests if it can be installed.  Is it possible that during testing `biocLite()` forks a separate instance of R with a working directory outside of `/home/gnomics/test` and thus doesn't find packrat's .Rprofile?

```
gcc -std=gnu99 -shared -o RSQLite.so connection.o driver.o exceptions.o extension-functions.o fetch.o fields.o importFile.o param_binding.o quick_column.o result.o sqlite-all.o utils.o -L/usr/lib/R/lib -lR
installing to /home/gnomics/test/packrat/lib/x86_64-pc-linux-gnu/3.0.1/RSQLite/libs
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
Error : package ‘DBI’ 0.2-7 was found, but >= 0.3.1 is required by ‘RSQLite’
Error: loading failed
Execution halted
ERROR: loading failed
* removing ‘/home/gnomics/test/packrat/lib/x86_64-pc-linux-gnu/3.0.1/RSQLite’
Loading required namespace: packrat
ERROR: dependency ‘RSQLite’ is not available for package ‘AnnotationDbi’
* removing ‘/home/gnomics/test/packrat/lib/x86_64-pc-linux-gnu/3.0.1/AnnotationDbi’
```

**Comment by kevinushey** [comment]
Hmm, yes, that's quite likely (but in the end the culprit would be `install.packages()`, or perhaps how `biocLite()` is calling `install.packages()`). And it looks like `install.packages()` indeed does spawn a separate R process to do teh installation, with:

```
cwd <- setwd(tmpd)
on.exit(setwd(cwd))
status <- system2(Sys.getenv("MAKE", "make"), c("-k -j", 
   Ncpus), stdout = output, stderr = output, env = env)
```

It's possible that we may need to set some environment variables to ensure child R processes get the appropriate `.libPaths()` (or, ignore the site-wide `.Rprofile`).

Can you try seeing if this prevents sourcing the site `.Rprofile`?

    Sys.setenv(R_PROFILE = ";;; disabled :::")

and then running `biocLite()`?

**Comment by gnomics** [comment]
Thanks!  This now works:
```
packrat::init()
Sys.setenv(R_PROFILE = ";;; disabled :::")
source("http://bioconductor.org/biocLite.R")
biocLite()
```
Two things:
1) Should it generally be safe to always run `Sys.setenv(R_PROFILE = ";;; disabled :::")` when working within packrat?
2) I saw that point in `?Startup` as well but was confused why `.Library.site` returns `character(0)` in a packrat managed directory.  Is `packrat/init.R` calling some function that blanks out `.Library.site`?

**Comment by kevinushey** [comment]
It should be safe, as long as you don't have any other bits in your `etc/Rprofile.site
