### ISSUE TITLE
handling setting different working directory while working interactively?

### ISSUE THREAD

**Issue by dpastoor** [rstudio/packrat#183]
I don't want to officially call it a bug (feature??) but have noticed packrat project, if I change the working directory I get the following error:

```
Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
```

While I appreciate the nature of not changing the working directory for projeccts, it is a 'necessary evil' when working with Rmarkdown documents in order to keep Paths to external data the same when working interactively vs when knitting if the Rmarkdown document is in a subfolder.

For example, given a simple project with the following structure:

- Rproj/
    - /data
   - /notebooks

putting Rmarkdown notebooks in the /notebooks folder and /data in the folder it makes sense to temporarily set the working directory to the location of the rmarkdown docs so when working interactively they will have the same paths (eg ../data/<data1.csv>.

Any solutions/recommendation beyond creating the packrat project in /notebooks which is not preferable due to larger projects having multiple folders that can contain Rmarkdown documents.

**Comment by kevinushey** [comment]
Hi @dpastoor,

Can you please clarify when, exactly, you see that error? Is it immediately after switching to a sub-directory in your packrat project? Also, is this from the console or within RStudio?

After entering 'packrat mode' for a given project, you should be able to switch directories as you please -- so I am curious when exactly the warning message is triggered.

**Comment by kevinushey** [comment]
Oh, is it possible that you have a 'stale' `.Rprofile` in one of your sub-directories that is attempting to read a `packrat/init.R` file?

**Comment by dpastoor** [comment]
Hi Kevin,

I get it whenever I restart my R session and try to load the first package. In addition, any packages after that one (including if I try to load that one again) will load. The error makes me 'concerned' as to whether it was falling back to my global library install or packrat was then initializing properly.

```
Restarting R session...

> library(PKPDmisc)
Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
> library(stringr)

```

Interestingly ,I get the same warning if I also try to improperly set the working directory (in the method I use) to the subdirectory immediately after restarting my r session. Eg given the Rmarkdown document lives in `/lab-notebook` if I am already in the `/lab-notebook` dir and try to run the following script I get an error.

```
Restarting R session...

> setwd(paste0(getwd(), "/lab-notebook"))
Error in setwd(paste0(getwd(), "/lab-notebook")) : 
  cannot change working directory
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
```

but If I run it again the error does not come up the second time

```
> getwd()
[1] "/Users/devin/Repos/ctm-rbp/lab-notebook"
> setwd(paste0(getwd(), "/lab-notebook"))
Error in setwd(paste0(getwd(), "/lab-notebook")) : 
  cannot change working directory
```


And in case it helps:

```
> devtools::session_info()
Session info-------------------------------------------------------------
 setting  value                       
 version  R version 3.1.2 (2014-10-31)
 system   x86_64, darwin14.0.0        
 ui       RStudio (0.98.1091)         
 language (EN)                        
 collate  en_US.UTF-8                 
 tz       America/New_York            

Packages-----------------------------------------------------------------
 package    * version date       source        
 devtools     1.6.1   2014-10-07 CRAN (R 3.1.2)
 packrat      0.4.2.1 2014-12-16 CRAN (R 3.1.2)
 PKPDmisc   * 0.2.3   2015-01-22 local         
 rstudioapi   0.1     2014-03-27 CRAN (R 3.1.2)
```

**Comment by kevinushey** [comment]
Thanks! I can reproduce this locally now; we'll get a fix for this soon (and we're planning a CRAN release in the near future so you should see that soon as well.)

**Comment by dpastoor** [comment]
Awesome! Good to know that isn't a 'feature' that I'd have to work around - figured you'd be on top of it :-)

And thanks for the tip - the method I was using was to reset the wd back to the project directory and run packrat::status() which seemed to work since it would give 

```
> packrat::status()
Up to date.
```

but when I actually ran packrat::on() as you just suggested, it actually showed it had loaded the global versions:

```
> packrat::on()
Unloading packages in user library:
- knitr, PKPDmisc
Packrat mode on. Using library in directory:
- "/Users/devin/Repos/ctm-rbp/packrat/lib"
```

**Comment by ekernf01** [comment]
Similar errors seem to have come up [elsewhere](https://community.rstudio.com/t/cant-initialize-existing-project-with-packrat/17218), and I am having a very similar issue even now in summer 2019. Here's my minimal example.

In an empty folder, put an R script as follows. 

```
packrat::init(project` = "path/to/your/folder")

x = matrix(rnorm(144), 12, 12)
FNN::get.knn(x, k = 2)
```

It should install FNN, restart R, create a new `.Rprofile`, and err as follows.

```
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
```
