### ISSUE TITLE
Packrat does not handle restore from 'CustomCRANLikeRepository' repositories

### ISSUE THREAD

**Issue by donarus** [rstudio/packrat#185]
Assume that we have two repositories called **CRAN** (official Cran mirror) and **CUSTOM** (eg. company's Cran mirror with private packages)

Packages in **CRAN** repository has in its *DESCRIPTION* file defined source as *CRAN*.
Packages in **CUSTOM** repository has in its *DESCRIPTION* file defined source as *CUSTOM*.

Now assume that we have two dependencies for our project - dependency **A** can be obtained from **CRAN** repository and private dependency **B** can be obtained only and only from **CUSTOM** repository.

It is possible to init packrat project by
```
options(repos = c(CUSTOM = 'http://custom.repo.com/15dev',
                  CRAN = 'http://cran.us.r-project.org'))
packrat::init(options = list(local.repos = c("R")))
```
and it is also possible to make a snapshot of the project
```
packrat::snapshot()
```

but it is not possible to restore it
```
packrat::restore()
```
which ends with error message
```
Installing xxxxx (1.2.3) ... Error in installPkg(pkgRecord, project, availablePkgs, repos, lib, cache) : 
  Failed to install xxxxx (1.2.3): sources missing at /home/...xxxxx.tar.gz
```

I think the cause is related to ```isFromCranlikeRepo``` function defined in *R/restore.R* and used by ```installPkg``` function defined in the same file.  In ```isFromCranlikeRepo```, there is check if given packageRecord inherits from **CustomCRANLikeRepository**
 ```
inherits(pkgRecord, "CustomCRANLikeRepository")
```
but pkgRecord objects are always returned as standard ```list``` structures.

To be concrete, I think that function ```packrat:::deserializePackages``` which is responsible for creating pkgRecord objects is implemented incorrectly and needs to be updated to return records with correct types.

**Comment by kevinushey** [comment]
Thanks for the detailed look into this issue -- I'll take a look and get this fixed soon.

**Comment by kevinushey** [comment]
I believe this commit fixes the problem -- it is somewhat more localized, but it should be less likely to cause regressions. We now double check the `source` field of the package record against the current repositories, and assume the package is from a CRAN-like repository if that source name is in the names of `getOption('repos')`.

Please try the development version of packrat:

    install_github('rstudio/packrat')

and let me know if this resolves the issue for you. Thanks!

**Comment by donarus** [comment]
Hi Kevin. I tried your fix and it seems that it resolves the issue. So I think we can close it for now. I'll try if everything else is working properly and I'll let you now in case something comes up.

Thanks!

**Comment by cronacronis** [comment]
Was it merged into CRAN version? Currently CRAN supplied `packrat_0.4.6-1`.

**Comment by donarus** [comment]
This is no longer issue in packrat 0.4.6 - it had been already resolved.
