### ISSUE TITLE
Using packrat with an Rstudio project and repmis on a 'managed' desktop can crash Rstudio

### ISSUE THREAD

**Issue by JonMinton** [rstudio/packrat#187]
The same chunk of code, using repmis::source_DropboxData to download a file, worked in one packrat Rstudio project but not another. Further details [here](http://stackoverflow.com/questions/28480435/code-chunk-using-repmisdropboxdata-works-in-one-rstudio-project-but-not-anothe)

Removing packrat on the version that didn't work, then doing install.packages(...), then enabling it again, solved the problem.

The issue occurred on a 'managed' office (university) computer that uses a [remote desktop config](http://www.gla.ac.uk/services/it/servicedefinitions/manageddesktops/forstaff/ssdremote/) - by default Rstudio writes to the remote desktop location rather than locally.
Call to Sys.info()

                     sysname                      release                      version                     nodename 
                   "Windows"                      "7 x64" "build 7601, Service Pack 1"               "DELL-JLCYJY1" 
                     machine                        login                         user               effective_user 
                    "x86-64"                     "jm383x"                     "jm383x"                     "jm383x
The version of the project that worked on home but not work machines is [here](https://github.com/JonMinton/gowell/commit/229b8ad219fe7697bca47a41f094fac4821d0ec7). The version that works on both home and work is [here](https://github.com/JonMinton/gowell/commit/0c72f8e28383d1bc6b3c6999d08a379b12c4463b). 
Another project, that has always worked at both the uni and home computers, is [here](https://github.com/JonMinton/pollution_area_associations/commit/8b280d9cc36f019d43eb7f78042769eb5f2349e1)

**Comment by kevinushey** [comment]
Thanks for the bug report -- this fix should be fixed with newer versions of RStudio; you can try the preview version at:

http://www.rstudio.com/products/rstudio/download/preview/

There was a race condition in the access of `LC_COLLATE` (which is modified by packrat, to do locale-independent sorting), which could cause a crash in RStudio.
