### ISSUE TITLE
help  ( ?xxxx ) does not work when use.cache=TRUE (tried on Linux)

### ISSUE THREAD

**Issue by tpalusga** [rstudio/packrat#194]
Hi guys :) Another small issue I detected :)

If U use Packrat with use.cache=TRUE, then you'll get symlinks instead of real folders in your `packrat/lib/OS_SPEC/R_VERSION` .. I looked into the R source code for 'help' method (https://github.com/wch/r-source/blob/580d78b91b35a08695300535180b8685fd183a9f/src/library/utils/R/help.R#L19-L23) and it seems that R constructs name of the package from the name of the folder where is this package stored.

Eg. package plyr is stored in
`~/develop/ext/packrat/lib/x86_64-pc-linux-gnu/3.0.2/plyr`
which symlinks to
`~/.config/packrat/v1/library/plyr/7dd935ee4050eaf2973108be2faf245e`

But from some reason, R uses the symlink name (7dd935ee4050eaf2973108be2faf245e) as a name for the package instead of plyr, so it logically can't find help sources for this package.

Maybe it could help to add another subfolder to the cache structure 
eg `~/.config/packrat/v1/library/plyr/7dd935ee4050eaf2973108be2faf245e/plyr` .. It is maybe redundant but it should work.

**Comment by kevinushey** [comment]
Thanks for the investigation! I believe you are correct that we should ensure the package name comes last in the cache; I'll make the appropriate changes in Packrat to make this work.

**Comment by donarus** [comment]
Thanks for the update, I'll try this fix as soon as possible and let you know if everything is working properly on Mac/Win/Linux... 

(Btw to preserve confusion - tpalusga is my second acc used to access our company repo and sometimes I forget to switch to my original account so don't be confused that sometimes I respond from different account :))

**Comment by donarus** [comment]
LINUX ... seems to be OK
WINDOWS ... seems to be OK
MAC.OSX ... ?? - I cannot verify it right now

**Comment by kevinushey** [comment]
Thanks for reporting and testing! The packrat cache is something that's still evolving so it's likely that there will be some small road bumps like this along the way -- please let us know if you encounter any other issues.

**Comment by donarus** [comment]
Hi, MAC.OSX also verified ... I think you can close the issue :)

**Comment by tpalusga** [comment]
Or I can do it (my 2nd acc... (@donarus)):)
