### ISSUE TITLE
packrat::init gives back 'cannot open URL'

### ISSUE THREAD

**Issue by Random-Primate** [rstudio/packrat#213]
After installing packrat and running ```packrat::init()``` I get the following error which in my opinion is trying to reach a site which is no longer available, additionally some other errors which I'm not sure are being generated by the first one.

Environment:
- OS X 10.10.3
- R version 3.2.0
- packrat   0.4.3
- cran (don't know how to get version for this one)

```
Fetching sources for packrat (0.4.3) ... OK (CRAN current)
Snapshot written to '/Users/user/RProjects/Data_Specialization/r_programming/packrat/packrat.lock'
Installing packrat (0.4.3) ... Error in download.file(url, destfile, method, mode = "wb", ...) : 
  cannot open URL 'http://cran.rstudio.com/src/contrib/packrat_0.4.3.tgz'
In addition: Warning message:
In download.file(url, destfile, method, mode = "wb", ...) :
  cannot open: HTTP status was '404 Not Found'
Warning in download.packages(pkgs, destdir = tmpd, available = available,  :
  download of package ‘packrat’ failed
Error in hash(descFile) : 
  No DESCRIPTION file at path '/Users/user/RProjects/Data_Specialization/r_programming/packrat/lib/x86_64-apple-darwin13.4.0/3.2.0/packrat/DESCRIPTION'!
```

From what I've read in this [issue](https://github.com/rstudio/packrat/issues/197) its also worth noting that I've got Biocinstaller v1.18.1

**Comment by kevinushey** [comment]
You'll need to either install the latest version of packrat from GitHub, or set `options(pkgType = "mac.binary.mavericks")`. See https://github.com/rstudio/packrat/issues/209 for more info.

**Comment by Random-Primate** [comment]
Works great, thanks.
