### ISSUE TITLE
snapshot fails after a silent failure to add an entry to lockfile 

### ISSUE THREAD

**Issue by yasminlucero** [rstudio/packrat#220]
After attempting to install `rmarkdown 0.6.1` with dependencies, I got this error on `rversions 1.0.0`:

```
packrat::snapshot()
Error in deserializePackages(utils::tail(df, -1)) : 
  The following dependencies are missing lockfile entries: rversions
```
I couldn't really work out why the lockfile entry was missing. I pasted below the traceback. It would have been more helpful if the error told me why the lockfile entry failed. 
```
> traceback()
7: stop("The following dependencies are missing lockfile entries: ", 
       paste(undeclaredDeps, collapse = ", "))
6: deserializePackages(utils::tail(df, -1))
5: readLockFile(lockFilePath(project))
4: getPackageRecordsLockfile(pkgNames, project = project)
3: getPackageRecords(inferredPkgsNotInLib, project = project, available = available, 
       check.lockfile = TRUE, fallback.ok = fallback.ok)
2: snapshotImpl(project, available, lib.loc, dry.run, ignore.stale = ignore.stale, 
       prompt = prompt && !dry.run)
1: packrat::snapshot()
```

As a workaround, I manually added the the entry to the lockfile, and that seemed to work out fine. 

The offending package is rversions 1.0.0 (from CRAN). My info: 

R version 3.2.0 (2015-04-16)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

**Comment by kevinushey** [comment]
It looks like `rversions` is a new dependency of `devtools`; I don't think `rmarkdown` has `devtools` in its dependency tree. Do you have `devtools` installed in your project?

I wonder if packrat is, for some reason, erroneously concluding that `rversions` is a dependency of your (older) version of `devtools`. It seems possible that we're constructing the dependency tree using information from `available.packages()` when we should be using the package's own `DESCRIPTION` file.

**Comment by yasminlucero** [comment]
Yes, here are the top level depedencies from my DESCRIPTION: 

   devtools (>= 1.8.0),
    rmarkdown (>= 0.6.1),
    packrat (>= 0.4.3),
    testthat (>= 0.9.1)

Let me know if you want the lock file too.

**Comment by shapiromatron** [comment]
@yasminlucero I'm having the same issue; how did you manually add to the lockfile? Specifically, how did you get the hash?

**Comment by lisovyk** [comment]
Same issue.
