### ISSUE TITLE
Packrat won't initialize (Windows, R 3.2)

### ISSUE THREAD

**Issue by nateGir** [rstudio/packrat#222]
I'm trying to initialize packrat as part of starting a new project. When I `packrat::init()` I get the following error:

```
> packrat::init()
Initializing packrat project in directory:
- "C:/Users/. . ."

Adding these packages to packrat:
            _         
    packrat   0.4.3-27

Fetching sources for packrat (0.4.3-27) ... FAILED
Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to download package from URL:
- "http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz"
```

I'm running:
Windows 8.1
R 3.2
Rstudio 99.441

Let me know if any other info is needed from me. Thanks.

**Comment by kevinushey** [comment]
Seems like it could have been an internet connectivity problem. Manually accessing the link right now (http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz) works for me.

**Comment by nateGir** [comment]
Forgot to mention that I thought of that and tried downloading the package outside of R and that it worked. I've also tried downloading and installing other Github only packages (ie: rMaps) and those worked as well so it seems like it's something that is packrat only.

**Comment by nateGir** [comment]
This is only happening when I try to initialize packrat in a project or package folder. When it attempts to fetch the packages it kicks back a 404 error. I generally don't have any problem downloading files from CRAN, GitHub, etc, and I'm not behind a firewall.

**Comment by kevinushey** [comment]
Interesting. Does calling `download.file("http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz")` within an R session also work for you? I am pretty confused as to what could be going on at this point...

If you could `debug()` the call to `snapshot()` and provide more details on exactly where it's failing I could try to narrow down what's going on.

**Comment by nateGir** [comment]
Here's the output from `download.file("http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz", 'test.tar.gz')`:
```
trying URL 'http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz'
Error in download.file("http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz",  : 
  cannot open URL 'http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz'
In addition: Warning message:
In download.file("http://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz",  :
  InternetOpenUrl failed: 'A redirect request will change a non-secure to a secure connection'
```

When I change the url to https;// . . .  I get the following:

```
trying URL 'https://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz'
Content type 'application/x-gzip' length 200 bytes
downloaded 108 KB

Warning message:
In download.file("https://github.com/rstudio/packrat/archive/1a91cdb290795c24cc0fda94177588b605525674.tar.gz",  :
  downloaded length 111220 != reported length 200
```
so at least something is downloading using that url.

`packrat::snapshot()` is falling, according to `debug()`, because:
```
Error: This project has not yet been packified.
Run 'packrat::init()' to init packrat.
```

When I try to `packrat::init()` I get the error from my first comment.

Could this be an issue of firewalls/windows security? I don't have trouble downloading and installing libraries but maybe packrat's 'automatic' nature is tripping some alarm. Just a thought.

**Comment by nateGir** [comment]
Even more info: I got R/Rstudio up and running on an Ubuntu 14.04.2 virtual machine and tried to initialize a packrat package and it worked fine.

**Comment by nateGir** [comment]
I updated to R 3.2.1 on my Windows box and packrat initializes again. Issue closed.
