### ISSUE TITLE
Question: Sharing packrat bundle to 2nd user with same OS and R, Rtools necessary?

### ISSUE THREAD

**Issue by instantkaffee** [rstudio/packrat#223]
In case I want to share a fully working packrat bundle to a colleague, does this user has to have a full Rtools installation working (i am askining as this is prerequisite to setup a packrat on my computer, but the 2nd user cannot install Rtools due to missing admin rights)? The user has the same OS (Windows 7) and R version running. From what I understand, the bundle should hold everything needed and Rtools is not needed - correct?

**Comment by kevinushey** [comment]
Hi @instantkaffee,

If you only share the package sources (note that this is the default with `packrat::bundle()` then your collaborators will need Rtools to rebuild from source.

As an alternative, you can use `packrat::bundle(include.lib = TRUE)`; after doing this you should be able to share that bundle with users running the same version of R + the same operating system.

Hope this helps,
Kevin
