### ISSUE TITLE
loading system-level libraries in Linux using extlib()

### ISSUE THREAD

**Issue by dasternberg** [rstudio/packrat#243]
I use RStudio Server on a shared server, where we manage most of our packages at the system level. I'm interested in using `extlib` to load roxygen2, but it doesn't have an argument to note that it should look for it at the system level rather than the user level, so I'm seeing:

```
> packrat::extlib(roxygen2)
Error in packrat::extlib(roxygen2) : object 'roxygen2' not found
```

Maybe I'm missing something?

**Comment by kevinushey** [comment]
`extlib()` will try to load a package from 'original' library paths, if available. Can you check the output of:

    .packrat_mutables$get("origLibPaths")

If this is `NULL` it's possible that packrat is doing the wrong thing (e.g. just using the result of `packrat:::getLibPaths()`.)

**Comment by dasternberg** [comment]
```
> get(".packrat_mutables", envir = asNamespace("packrat"))$get("origLibPaths")
NULL
```

**Comment by kevinushey** [comment]
I think the situation should be improved here now -- `extlib` now tries to determine what the default library paths are for a non-packrat R session, and uses those paths when attempting to load a library.

Can you try out the development version of packrat and let me know if that resolves your issue?

**Comment by dasternberg** [comment]
@kevinushey just tested the current master and it worked. thanks!
