### ISSUE TITLE
Source from Bioconductor: incorrect URLs from getBiocRepos()? 

### ISSUE THREAD

**Issue by vasiliosz** [rstudio/packrat#247]
Hi, 
I'm using the current stable Bioconductor version (3.1) with latest R (3.2.2). 
However, when snapshotting with packrat it fails to download sources from Bioconductor (but CRAN works fine). 
```
Fetching sources for AnnotationDbi (1.30.1) ... curl: (22) The requested URL returned error: 404 Not Found
```
I think this is due to the BioC being (incorrectly) set to version `3.2` instead of  `3.1`
I.e. the correct prefix url should be `http://bioconductor.org/packages/3.1/...` rather than `http://bioconductor.org/packages/3.2/...`. 

This seems to stem from `getBiocRepos()` which uses the R version to create the Bioconductor version prefix. So with R version **3.2**.2, it builds the latter URL above. 

```
getBiocRepos <- function() {

  rVersion <- unlist(getRversion())
  rv <- paste(rVersion[[1]], rVersion[[2]], sep = ".")
  prefix <- sprintf("http://bioconductor.org/packages/%s", rv)

  c(
    BioCsoft  = file.path(prefix, "bioc"),
    BioCann   = file.path(prefix, "data/annotation"),
    BioCexp   = file.path(prefix, "data/experiment"),
    BioCextra = file.path(prefix, "extra")
  )
}
```

This leads to `packrat::snapshot()` not finding the sources of my BioC packages, since it's looking in the BioC 3.2 url.

If I use `setRepositories()` to set Bioconductor repos, it correctly sets them to Bioc v 3.1. But since packrat still fails after setting this, I can only assume `getBiocRepos()` is overriding this? 

```
> getOption("repos")
                                                   CRAN 
                            "https://cran.rstudio.com/" 
                                               BioCsoft 
           "https://bioconductor.org/packages/3.1/bioc" 
                                                BioCann 
"https://bioconductor.org/packages/3.1/data/annotation" 
                                                BioCexp 
"https://bioconductor.org/packages/3.1/data/experiment" 
                                              BioCextra 
          "https://bioconductor.org/packages/3.1/extra"
```

**Comment by vasiliosz** [comment]
To add, when I forked packrat and temporarily hardcoded the 3.1 prefix to Bioconductor in the `getBiocRepos()` the snapshotting works again. 

```
Fetching sources for AnnotationDbi (1.30.1) ... OK (Bioconductor current)
```

**Comment by kevinushey** [comment]
@vasiliosz thanks, you're right -- I think the original intention was to avoid using a wrong / out of sync `BiocInstaller` package installation to determine the BioC URLs, but it looks like packrat is getting it wrong here.

**Comment by kevinushey** [comment]
This should be resolved here: https://github.com/rstudio/packrat/commit/5c83f706de7221348fcfbf6208d430fb6abe287a

Thanks for reporting!
