### ISSUE TITLE
Error on restore with project started under older Packrat

### ISSUE THREAD

**Issue by jcheng5** [rstudio/packrat#252]
I got this error:

```
Installing colorspace (1.2-4) ...
Error in !quiet : invalid argument type
```

Due to:

```
> packrat::opts$quiet.package.installation()
NULL
```

Worked around by calling `packrat::opts$quiet.package.installation(TRUE)`.

Not sure exactly what version of packrat I used to start this project but clearly it was before we had these options.

**Comment by mateusz-gorski-hello** [comment]
Hi, I am experiencing the problem you described. How can it be fixed without downloading new version ?

**Comment by kevinushey** [comment]
The simplest way to work around this is to run:

    packrat::opts$quiet.package.installation(TRUE)

You should only need to run this once for each (pre-existing) project. Alternatively, you can try updating to the latest version of packrat on GitHub, which shouldn't err on this anymore.

Sorry for the inconvenience!
