### ISSUE TITLE
`packrat::clean()` removes required Shiny dependencies

### ISSUE THREAD

**Issue by warmdev** [rstudio/packrat#253]
Running `packrat::clean()` in a Shiny project removes `bitops`, `caTools` and `RJSONIO`, which are required by RStudio to run the Shiny app locally. After the removal, click "Run App" would result in a popup window that says

> Install Shiny Package: Running Shiny applications requires installation of an updated version of the shiny package. Do you want to install shiny now?

Select "Yes" and RStudio will reinstall the three packages mentioned above.

OS: Tested on both Windows 7 and Xubuntu 15.10
RStudio: 0.99.486
packrat: 0.4.5
shiny: 0.12.2

**Comment by kevinushey** [comment]
Shiny (from version 0.12.2) no longer depends on `RJSONIO`; it instead uses `jsonlite`. This sounds more like a bug in RStudio (installing unrequired dependencies).

**Comment by kevinushey** [comment]
This should be resolved in the latest RStudio preview; please give it a shot at https://www.rstudio.com/products/rstudio/download/preview/.

**Comment by warmdev** [comment]
This preview version (0.99.745) solves the problem for `RJSONIO`, but not for `bitops` and `caTools`. The latter two are still being removed by `packrat::clean()`, while required and reinstalled by RStudio.

**Comment by kevinushey** [comment]
Thanks; I think RStudio is erroneously picking up those dependencies -- compare with

```R
> as.data.frame(devtools::package_deps("shiny"))
    package installed available diff
1    digest     0.6.8     0.6.8    0
2 htmltools     0.2.6     0.2.6    0
3    httpuv     1.3.3     1.3.3    0
4  jsonlite    0.9.17    0.9.17    0
5      mime       0.4       0.4    0
6        R6     2.1.1     2.1.1    0
7      Rcpp    0.12.1    0.12.1    0
8     shiny    0.12.2    0.12.2    0
9    xtable     1.7-4     1.7-4    0
```
