### ISSUE TITLE
Error in packrat during deployment on shinyapps.io

### ISSUE THREAD

**Issue by sharang17** [rstudio/packrat#254]
I'm building a stock analyzer using shiny. After using init and snapshot in my working directory I get the following error. Please do help me out :)

[2015-11-04T08:06:22.248871365+0000] Installing R package: stockPortfolio (1.2)
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'packrat/init.R': No such file or directory
Execution halted

**Comment by kippandrew** [comment]
Closing because this is a shinyapps.io issue.
