### ISSUE TITLE
Separate appDependencies() from init() and snapshot()

### ISSUE THREAD

**Issue by benb111** [rstudio/packrat#258]
Wrote a post about this in the packrat-discuss Google Group: https://groups.google.com/forum/#!topic/packrat-discuss/m0kKGy_W3-0.

Have you considered allowing users to init() or restore() without scanning the subdirectories for libraries to include?  That would be very useful for me, and would make it easier to work around any bugs in the scanning (which I seem to be running into when using packrat with RStudio).  As it is, if there is any issue in the auto-discovery of packages, you can't use packrat at all.  And the basic functionality of snapshotting to source and building from source doesn't seem to require this.

**Comment by benb111** [comment]
To make this more concrete, I'm currently blocked from snapshotting with this error:

    Error: Unable to retrieve package records for the following packages:
    - 'GLMMGibbs', 'R6testA', 'bread', 'breakfast', 'foo', 'foo1', 'foo2', 'oatmeal', 'pkgA', 'pkgB', 'sashimi', 'testRcppClass', 'testRcppModule', 'yags'
In addition: There were 42 warnings (use warnings() to see them)

None of these are real dependencies.  For example, when I grep for oatmeal, I see

    packrat/lib/x86_64-apple-darwin14.1.0/3.1.3/packrat/tests/testthat/helper-packrat.R:  cat("library(oatmeal)", file = file.path(libraryRootDir(project), "lib-current.R"), sep = "\n")

So one problem is that packrat sees this as a dependency, but really I'd just like to disable the search for dependencies altogether.

**Comment by kevinushey** [comment]
Ack, thanks. It looks like packrat is not excluding its own directory when crawling for dependencies, and this is an artefact of the fact that we now include tests in the CRAN tarball. :/

I agree it could also be useful to control whether packrat automatically infers dependencies -- this would put the onus on the user to determine what they want in their library (and want to snapshot) but I am sure is desired by more users than just yourself!

**Comment by kevinushey** [comment]
Hmm, I'm a bit confused now because I can't reproduce this on OS X. Can you paste your `sessionInfo()`? It looks like we _do_ explicitly omit the `packrat/` directory; for some reason that's being missed in your case?

**Comment by benb111** [comment]
Thanks for the quick response!  Here's the sessionInfo()

    > sessionInfo()
    R version 3.1.3 (2015-03-09)
    Platform: x86_64-apple-darwin14.1.0 (64-bit)
    Running under: OS X 10.10.5 (Yosemite)

    locale:
    [1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

    attached base packages:
    [1] stats     graphics  grDevices utils     datasets  methods   base

    loaded via a namespace (and not attached):
    [1] packrat_0.4.6-1 tools_3.1.3

**Comment by kevinushey** [comment]
Can you provide a small reproducible example to show how exactly you're creating the project + calling `snapshot()`? For example, the following (from the terminal) works fine for me:

```
cd $TMPDIR
mkdir packrat-test
cd packrat-test
R -e "packrat::init()"
R -e "packrat::snapshot()"
```

If I understand correctly, that should fail in your case (because dependencies within the `packrat/` directory are being picked up, for some reason).

**Comment by benb111** [comment]
Oh I think I have an idea.  I have a packrat project in a subdirectory.  So maybe that's not getting excluded?

I think it will be hard to get this dependency parsing right in all cases, which is why I'd love to have the option to have it decoupled from the core functionality.  Agree it puts the onus on the user, but I would love that level of control.

I'm going to see if I can reproduce this without having the packrat project in a subdirectory

**Comment by kevinushey** [comment]
Ah, that would definitely be it. Packrat is smart enough to exclude its own `packrat/` directory (when it's managing a top-level project) but not when it's discovered as a sub-directory. This would be true of other packages discovered as sub-directories, I think.

**Comment by benb111** [comment]
Yup, that was it.  Perhaps it would make sense to exclude all subdirectories called packrat, regardless of how deep they are?

Let me also give you some background on why I have a packrat project as a subdirectory because you might have a better idea.  I have a directory structure that looks like

    R/
      packrat/
      shiny_app_1/
      shiny_app_2/

I want all of the shiny apps to share the same packrat setup, so I created a symlink inside the each shiny app to the parent packrat directory.  That way when shiny server runs the app it uses packrat.  (And this seemed lighter weight than having a separate packrat project for each app.)

**Comment by kevinushey** [comment]
Nice! Seems like a very nice use case, and I definitely think packrat can and should support this sort of workflow.

**Comment by micstr** [comment]
I tried benb111 approach but have had no luck with a solution. Please see http://stackoverflow.com/questions/35359707/in-rstudio-how-to-deploy-app-to-shiny-server-with-packrat for error message
