### ISSUE TITLE
with_extlib and parent.frame

### ISSUE THREAD

**Issue by mplourde** [rstudio/packrat#259]
`with_extlib` has an `envir` argument that appears to default to the calling frame. This works fine in the global environment.

```r
packageVersion('packrat')
# [1] '0.4.6.2'

packrat::on()
a <- 1
packrat::with_extlib('devtools', a)
# [1] 1
```

But fails when called from within a function:

```r
f <- function() {
    b <- 1
    packrat::with_extlib('devtools', b)
}

f()
# Error: object 'b' not found
```

**Comment by kevinushey** [comment]
Thanks! This should be resolved with https://github.com/rstudio/packrat/commit/5df8e493f71a5e27056906556e4c180e2a644089.
