### ISSUE TITLE
extlib with RRO

### ISSUE THREAD

**Issue by mplourde** [rstudio/packrat#260]
When running RRO:

```r
packrat:::getDefaultLibPaths()
# [1] "Multithreaded BLAS/LAPACK libraries detected. Using 4 cores for math algorithms."
```

This causes the `extlib`, etc. functions to fail.

**Comment by kevinushey** [comment]
Can you tell Revolution R not to print their banned when R is called with the `--slave` argument?

This can be worked around in `packrat` anyhow.

**Comment by kevinushey** [comment]
Closed via https://github.com/rstudio/packrat/commit/bc2324120e1c815e13f05ece9377d5a847073bd1.
