### ISSUE TITLE
Packrat fails to download source from Github repos

### ISSUE THREAD

**Issue by erinshellman** [rstudio/packrat#269]
Hi there,

I'm trying to take snapshots after installing packages with`devtools::install_github()`, but Packrat fails to download the source:  

```
> packrat::snapshot()

Adding these packages to packrat:
                 _      
    MatrixModels   0.4-1
    SparseM        1.7  
    car            2.1-1
    pbkrtest       0.4-6
    quantreg       5.21 


Upgrading these packages already present in packrat:
                    from         to
    packrat     0.4.6-12   0.4.6-13
    rmarkdown      0.9.2      0.9.5

Fetching sources for packrat (0.4.6-13) ... FAILED
Fetching sources for rmarkdown (0.9.5) ... FAILED
Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to download package from URL:
- 'http://github.com/rstudio/packrat/archive/71364778269841eedf2a8748055d759c858ff3a0.tar.gz'
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to download package from URL:
- 'http://github.com/rstudio/rmarkdown/archive/1a76e23482bbdaf06d82a3c3e2c968d974e42d72.tar.gz'
```

I've confirmed that those links do exist, so not sure what the problem is. My session info is here:

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.11.3 (El Capitan)

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] dplyr_0.4.3

loaded via a namespace (and not attached):
 [1] magrittr_1.5     R6_2.1.1         assertthat_0.1   formatR_1.2.1    parallel_3.2.3   DBI_0.3.1        tools_3.2.3      yaml_2.1.13      memoise_1.0.0   
[10] Rcpp_0.12.2      stringi_1.0-1    knitr_1.12.3     digest_0.6.9     stringr_1.0.0    packrat_0.4.6-13 devtools_1.10.0 
```

**Comment by kevinushey** [comment]
Any chance this is an intermittent error?

What happens if you execute:

    packrat:::download('http://github.com/rstudio/packrat/archive/71364778269841eedf2a8748055d759c858ff3a0.tar.gz')

directly? If this fails, can you also give the output of:

    getOption("download.file.method")
    getOption("download.file.extra")

**Comment by erinshellman** [comment]
Looks like download isn't a function in packrat, did you mean something else?

```
packrat::download('http://github.com/rstudio/packrat/archive/71364778269841eedf2a8748055d759c858ff3a0.tar.gz')
Error: 'download' is not an exported object from 'namespace:packrat'
```
The output of the options is:
```
getOption("download.file.method")
[1] "curl"
getOption("download.file.extra")
NULL
```

**Comment by kevinushey** [comment]
It's an unexported function, so you need to access it using three colons (`:::`) rather than two (`::`).

**Comment by erinshellman** [comment]
In that case it says:
```
packrat:::download('http://github.com/rstudio/packrat/archive/71364778269841eedf2a8748055d759c858ff3a0.tar.gz')
Error in if (!grepl("\\b-L\\b", extra)) extra <- paste(extra, "-L") : 
  argument is of length zero
```

**Comment by kevinushey** [comment]
Thanks -- looks like packrat is incorrectly assuming that `download.file.extra` is a string. I'll get this fixed soon!

**Comment by erinshellman** [comment]
Yay, I appreciate it!

**Comment by kevinushey** [comment]
Okay, I believe this should be resolved with the latest version of packrat -- can you give it a test and let me know how it goes?

Thanks!

**Comment by erinshellman** [comment]
hmm, I'm seeing this now:

```
packrat::snapshot()
Error in visited[[rec$name]] <- rec : 
  wrong args for environment subassignment
```

**Comment by kevinushey** [comment]
Any chance you can print a traceback, or use `options(error = recover)` and tell me what the `rec` variable is? My guess is that `rec` itself must be `NULL`...

**Comment by erinshellman** [comment]
sure: 

```
traceback()
5: visit(rec$depends)
4: visit(packageRecords)
3: flattenPackageRecords(inferredPkgRecords, depInfo = TRUE, sourcePath = TRUE)
2: snapshotImpl(project, available, lib.loc, dry.run, ignore.stale = ignore.stale, 
       prompt = prompt && !dry.run)
1: packrat::snapshot()
```

**Comment by kevinushey** [comment]
I think this commit may have fixed it: https://github.com/rstudio/packrat/commit/021f122186cb2b5f80831d46d3b436411852c765

Can you give it another shot with latest master? (Sorry for the breakage!)

**Comment by erinshellman** [comment]
Booya! Thanks!
```
Upgrading these packages already present in packrat:
                    from         to
    packrat     0.4.6-12   0.4.6-16
    rmarkdown      0.9.2      0.9.5

Fetching sources for dplyr (0.4.3.9000) ... OK (GitHub)
Fetching sources for packrat (0.4.6-16) ... OK (GitHub)
Fetching sources for rmarkdown (0.9.5) ... OK (GitHub)
```

**Comment by mtreadwell** [comment]
I am still having trouble with this issue.

I have downloaded the most recent version of the package:
`devtools::install_github('rstudio\packrat')`

Then:
`packrat::init("<directory>")`

Gives:

    Fetching sources for packrat (0.4.6-17) ... FAILED
    Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
      Errors occurred when fetching source files:
    Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
      Failed to download package from URL:
    - "http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz"

With `traceback()`

    5: stop("Errors occurred when fetching source files:\n", errors)
    4: snapshotSources(project, activeRepos(project), allRecordsFlat)
    3: snapshotImpl(project, available.packages(contrib.url(activeRepos(project))), 
           lib.loc = NULL, ignore.stale = TRUE, fallback.ok = TRUE)
    2: withCallingHandlers(expr = {
           if (isPackratModeOn()) 
               off()
           packify(project = project, quiet = TRUE)
           augmentRprofile(project)
           options <- initOptions(project, opts)
           snapshotImpl(project, available.packages(contrib.url(activeRepos(project))), 
               lib.loc = NULL, ignore.stale = TRUE, fallback.ok = TRUE)
           restore(project, overwrite.dirty = TRUE, restart = FALSE)
           file.copy(instInitFilePath(), file.path(project, "packrat", 
               "init.R"))
           updateSettings(project, options)
           symlinkSystemPackages(project = project)
           message("Initialization complete!")
           if (enter) {
               setwd(project)
               if (!restart || !attemptRestart()) 
                   on(project = project, clean.search.path = TRUE)
           }
           invisible()
       }, error = function(e) {
           for (i in seq_along(priorStructure)) {
               file <- names(priorStructure)[[i]]
               fileExistedBefore <- priorStructure[[i]]
               fileExistsNow <- file.exists(file)
               if (!fileExistedBefore && fileExistsNow) {
                   unlink(file, recursive = TRUE)
               }
           }
       })
    1: packrat::init("<directory>")

Trying this:

    packrat:::download('http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz')

Gives:

    Error in download.file(url = url, method = method, extra = extra, ...):
         argument "destfile" is missing, with no default    

With `traceback()`

    4: download.file(url = url, method = method, extra = extra, ...)
    3: withCallingHandlers(download.file(url = url, method = method, 
           extra = extra, ...), warning = function(w) {
           caughtWarning <<- w
           invokeRestart("muffleWarning")
       })
    2: downloadFile(url, method, ...)
    1: packrat:::download("http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz")

**Comment by kevinushey** [comment]
Sorry, I should have asked you to specify a `destfile` argument, e.g.

`packrat:::download(url, destfile = tempfile())`

What version of R are you using? Are you running RStudio? If so, what version?

What's the output of `getOption('download.file.method')`? What about `getOption('download.file.extra')`?

**Comment by mtreadwell** [comment]
R-3.2.2
RStudio Version 0.99.473

    > getOption('download.file.method')
    [1] "wininet"
    > getOption('download.file.extra')
    NULL

    > packrat:::download("http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz", destfile = tempfile())
    trying URL 'http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz'
    Error in download.file(url = url, method = method, extra = extra, ...) : 
      cannot open URL 'http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz'
    > traceback()
    4: download.file(url = url, method = method, extra = extra, ...)
    3: withCallingHandlers(download.file(url = url, method = method, 
           extra = extra, ...), warning = function(w) {
           caughtWarning <<- w
           invokeRestart("muffleWarning")
       })
    2: downloadFile(url, method, ...)
    1: packrat:::download("http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz", 
           destfile = tempfile())

**Comment by kevinushey** [comment]
Hmmm, that's very odd as the same call works for me on a Windows 10 machine with R 3.2.3 patched (although with the latest release of RStudio).

What if you just use `download.file()`, e.g.

```R
url <- "http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz"
download.file(url, destfile = tempfile())
```

Does that succeed? What if you set `options(download.file.method = "internal")`?

**Comment by mtreadwell** [comment]
Hmmmm:

    > download.file(url, destfile = tempfile())
    trying URL 'http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz'
    Error in download.file(url, destfile = tempfile()) : 
      cannot open URL 'http://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz'
    In addition: Warning message:
    In download.file(url, destfile = tempfile()) :
      InternetOpenUrl failed: 'A redirect request will change a non-secure to a secure connection'

Seeing the last warnings there I tried https instead and it worked:

    > url <- "https://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz"
    > download.file(url, destfile = tempfile())
    trying URL 'https://github.com/rstudio/packrat/archive/9966a824ade72e5fecf6f770c9b75d2f1a6d8987.tar.gz'
    Content type 'application/x-gzip' length 119342 bytes (116 KB)
    downloaded 116 KB

**Comment by kevinushey** [comment]
That seems odd that going from non-secure to secure would be a failure...

Either way, packrat does construct non-https URLs behind the scenes so this is a bug in packrat. In the interim, you should be able to work around this by using `options(download.file.method = "internal")`.

**Comment by kevinushey** [comment]
I just made a commit to master that should resolve this (prefer `https` for GitHub downloads when possible). Can you let me know if that works for you?

**Comment by kevinushey** [comment]
Also, it looks like this is a setting that can be toggled in Internet Explorer (`wininet` implies the use of the same download machinery that Internet Explorer uses): http://kb.tableau.com/articles/knowledgebase/resolving-internet-communication-error-secure-nonsecure

You might try changing that to see if it makes a difference.

**Comment by mtreadwell** [comment]
that one worked! thanks so much. you've been super responsive. can't tell you how much i appreciate it.

**Comment by kevinushey** [comment]
No problem! Glad we were able to find a resolution :)
