### ISSUE TITLE
Allow sources to be installed from bitbucket / gitorious

### ISSUE THREAD

**Issue by imanuelcostigan** [rstudio/packrat#27]
Let's make it a bit more remote agnostic...

**Comment by fjuniorr** [comment]
I just noticed that [#382](https://github.com/hadley/devtools/issues/382) is closed in the devtools package. Any chance we might see this issue anytime soon?

**Comment by imanuelcostigan** [comment]
I'm doing a bit of Bitbucket work via https://github.com/hadley/devtools/issues/1157 at https://github.com/imanuelcostigan/devtools/tree/feature-bitbucket-parity-1157

**Comment by imanuelcostigan** [comment]
@fjuniorr If I am not mistaken, packrat [in places](https://github.com/rstudio/packrat/blob/ba2626b791924eba7aea73060d27267d1d3b24bb/R/pkg.R#L264) assumes package is from Github, particularly by using custom DESCRIPTION fields like `GithubSHA1` rather than the more source agnostic `RemoteSha` in more recent versions of devtools
