### ISSUE TITLE
can't initialize using https Cran repo in packrat.lock file

### ISSUE THREAD

**Issue by machow** [rstudio/packrat#273]
I have a project whose `packrat.lock` uses a Cran repo with the https protocol. I am unable to clone and initialize the project. However, when I change the repo url to use http, everything works fine.

**R console output with https cran repo**

```
Packrat is not installed in the local library -- attempting to bootstrap an installation...
> No source tarball of packrat available locally
> Using user-library packrat (0.4.6.4) to bootstrap this project
Warning: unable to access index for repository https://cran.mtu.edu/bin/macosx/mavericks/contrib/3.1
Installing R6 (2.1.1) ... 
Error in installPkg(pkgRecord, project, availablePkgs, repos, lib, cache) : 
  Failed to install R6 (2.1.1): sources missing at /Users/machow/Dropbox/Repo/science/dissertation/papers/test2/packrat/src/R6/R6_2.1.1.tar.gz
```

This also occurs if I change the Cran repo to `https://cran.rstudio.com`. AFAIK, packrat uses the `https` protocol by default for my project, since I have these settings selected in Rstudio..

![image](https://cloud.githubusercontent.com/assets/2574498/13256637/7e04b344-da19-11e5-8d3f-07989f1fbe78.png)

**packrat.lock (truncated)**

```
PackratFormat: 1.4
PackratVersion: 0.4.6.4
RVersion: 3.1.3
Repos: BioCsoft=http://bioconductor.org/packages/3.0/bioc,
    BioCann=http://bioconductor.org/packages/3.0/data/annotation,
    BioCexp=http://bioconductor.org/packages/3.0/data/experiment,
    BioCextra=http://bioconductor.org/packages/3.0/extra,
    CRAN=https://cran.rstudio.com
```

**Comment by kevinushey** [comment]
What operating system are you running with? What's the output of running `getOption("download.file.method")` or `getOption("download.file.extra")`?

Are you able to restore the project 'manually' from the command line, e.g. with a simple

    packrat::restore()

or does that emit the same error?

**Comment by machow** [comment]
I'm Mac Osx 10.10.3, but also get the issue on a computer cluster running CentOS 5.8. It looks like the options you mention aren't set, so maybe that has something to do with it? packrat::restore() omits the same error.

**On Mac w/ packrat::restore and checking options**
```
R version 3.1.3 (2015-03-09) -- "Smooth Sidewalk"
Copyright (C) 2015 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin13.4.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

Packrat is not installed in the local library -- attempting to bootstrap an installation...
> No source tarball of packrat available locally
> Using user-library packrat (0.4.6.4) to bootstrap this project
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1
Installing GlobalOptions (0.0.8) ... 
Error in installPkg(pkgRecord, project, availablePkgs, repos, lib, cache) : 
  Failed to install GlobalOptions (0.0.8): sources missing at /Users/machow/Dropbox/Repo/science/dissertation/papers/test3/packrat/src/GlobalOptions/GlobalOptions_0.0.8.tar.gz

> packrat::restore()
Warning: unable to access index for repository https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1
Installing GlobalOptions (0.0.8) ... 
Error in installPkg(pkgRecord, project, availablePkgs, repos, lib, cache) : 
  Failed to install GlobalOptions (0.0.8): sources missing at /Users/machow/Dropbox/Repo/science/dissertation/papers/test3/packrat/src/GlobalOptions/GlobalOptions_0.0.8.tar.gz

> getOption('download.file.extra')
NULL

> getOption('download.file.method')
NULL
> 
```

**Comment by kevinushey** [comment]
Can you tell me what the output of the following commands is?

    url <- "https://cran.rstudio.com/bin/macosx/mavericks/contrib/3.1"
    packrat:::download(url, destfile = tempfile())
    packrat:::secureDownloadMethod()

Can you also try updating to the development version of packrat, with

    devtools::install_github('rstudio/packrat')

and see if that helps?

**Comment by machow** [comment]
Ah, you beat me to it! I tried after installing packrat from github (so, from 4.6.1 to 4.6-19) and it worked. Thanks for the quick response!

**Comment by kevinushey** [comment]
Great to hear, thanks! Once we're confident that there aren't any outstanding bugs we'll get a new version pushed to CRAN as well.
