### ISSUE TITLE
Recursive symlinks on Windows

### ISSUE THREAD

**Issue by rappster** [rstudio/packrat#278]
I like the philosophy behind packrat a lot and every once in a while I give it a new try, but I'm always thrown off by the fact that the symlinks seem to be off somehow on Windows. Any chance of looking into this?

![2016-02-26 16_46_19-new issue rstudio_packrat](https://cloud.githubusercontent.com/assets/1205659/13356997/8e4cdc36-dca8-11e5-8943-5b59ba6cd77c.png)

When running `git add --all`:
![2016-02-26 16_44_30-clipboard](https://cloud.githubusercontent.com/assets/1205659/13357018/a8446c58-dca8-11e5-8f5d-7b4a9d720e9c.png)

```
> sessionInfo()
R version 3.2.3 (2015-12-10)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252   
[3] LC_MONETARY=German_Germany.1252 LC_NUMERIC=C                   
[5] LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] tools_3.2.3     packrat_0.4.6-1
```

**Comment by kevinushey** [comment]
I'm hopeful that https://github.com/rstudio/packrat/pull/277 will resolve this issue -- once that's finished and merged, would be willing to test the development version of packrat?

**Comment by rappster** [comment]
Sure! Just let me know when it's done.

**Comment by kevinushey** [comment]
Hi @rappster,

This should (hopefully) be resolved with the latest version of packrat -- it should clean up any erroneously generated symlinks, and ensure they don't get generated in the future.

Can you try the development version of packrat, with

    devtools::install_github('rstudio/packrat')

and let me know how it goes? Packrat should automatically clean up those symlinks next time it launches (e.g. with `packrat::on()`).

**Comment by rappster** [comment]
Hi @kevinushey, 

awesome, looks good now! Thanks a lot for fixing this!

**Comment by kevinushey** [comment]
Awesome, thanks!
