### ISSUE TITLE
Symlinking not working on latest version

### ISSUE THREAD

**Issue by raubreywhite** [rstudio/packrat#288]
my code:

setwd("'H:/xSmallProjects/test")
packrat::init()

Everything then works, it gets down to "Initialization complete!", then restarts R and I get this error:

Error in file(con, "rb") : cannot open the connection
In addition: Warning message:
In file(con, "rb") :
  cannot open file 'H:/xSmallProjects/test/packrat/lib-R/base/DESCRIPTION': No such file or directory

I just rolled back my version of packrat to 0.4.4 and everything works perfectly.

**Comment by kevinushey** [comment]
Thanks! This should be resolved with https://github.com/rstudio/packrat/commit/2bbc359d5d53f9c5061ffd48ec2b770532d693e0 (as per your comments).
