### ISSUE TITLE
packrat::on() very slow (5+ minutes)

### ISSUE THREAD

**Issue by raubreywhite** [rstudio/packrat#290]
When I turn packrat on, the command runs very quickly, however, afterwards RStudio will not accept any input for at least 5 minutes while it processes and updates the "packages" tab.

**Comment by kevinushey** [comment]
You mentioned in a separate post that you were running on a networked drive -- I wonder if the dependency detection code, or something else, is taking an inordinate amount of time?

You might want to try disabling the Package pane:

<img width="585" alt="screen shot 2016-04-06 at 11 25 26 am" src="https://cloud.githubusercontent.com/assets/1976582/14328161/6691c0c4-fbea-11e5-834e-5a7d88d7b280.png">

**Comment by raubreywhite** [comment]
Thanks for the suggestion, I just tried it and it didn't make any difference.

I did find something *extremely* strange though.

If I run packrat::on() while in RStudio project mode, it will hang for ~5 minutes after the command and refuse to take any input. If I run the same source code outside of RStudio project mode, it will only hang for ~5 seconds.

I then went into my package options and tried:
- disabling auto.snapshot
- disabling packrat

Neither of those made it any faster in project mode. 

So I'm not quite sure what is happening, but since it works well outside of project mode I will just work in that environment :-)

**Comment by raubreywhite** [comment]
The above also applies when I use "packrat::on(auto.snapshot=FALSE)"

**Comment by raubreywhite** [comment]
I also walked through the source code of packrat::on() and ran it line-by-line to see where it hung.

In project mode, everything works perfectly well until I hit the line

packrat:::setLibPaths(c(localLib, packrat:::libExtDir(project)))

(in function packrat:::afterPackratModeOn)

Then RStudio hangs for 5 minutes and won't respond.

I also tried restarting my R session, entering project mode and then immediately running 
a) .libPaths("F:/_SM/SMAO/Faggrupper/SMX/Sykdommer/Hepatitt C/Burden of disease/Hinta_graphs_SSI/packrat/lib")
b) packrat:::setLibPaths("F:/_SM/SMAO/Faggrupper/SMX/Sykdommer/Hepatitt C/Burden of disease/Hinta_graphs_SSI/packrat/lib")

Neither of these caused RStudio to hang at all.

**Comment by raubreywhite** [comment]
Cross posting from https://support.rstudio.com/hc/en-us/community/posts/210311327-packrat-on-very-slow-5-minutes-

###########

Hi Kevin,



Thanks for the suggestion/reply.



https://gist.github.com/raubreywhite/dd7398f66b6d9f5d2845624e61b3c8b9



I ran two profiles:

Profile 1: not in project mode (takes about 5 seconds to run in RStudio)

Profile 2: in project mode (takes about 5 minutes to run in RStudio)



I have included 5 files here.

1. "commands.R" the syntax I used to run the two profiles

2. "summary_startup.txt" the R console log for profile 1

3. "summary_startup_project.txt" the R console log for profile 2

4. "startup.Rprof" the r profile file for profile 1

5. "startup_project.Rprof" the r profile file for profile 2



This code also runs very quickly when I run it in the basic R console.



I'm also cross-posting this to https://github.com/rstudio/packrat/issues/290



Thanks,

Richard

**Comment by kevinushey** [comment]
The profiler output suggests R is spending almost all of its time within `list.files()`:

```
$by.self
                                     self.time self.pct total.time total.pct
"list.files"                            194.90    84.81     194.90     84.81
```

And I believe this is being caused by RStudio calling `packrat:::appDependencies()` behind the scenes:

```
$by.total
                                       total.time total.pct self.time self.pct
"<Anonymous>"                              229.82    100.00      0.18     0.08
"suppressWarnings"                         224.68     97.76      0.00     0.00
"withCallingHandlers"                      224.68     97.76      0.00     0.00
"doTryCatch"                               223.22     97.13      0.22     0.10
"tryCatch"                                 223.22     97.13      0.00     0.00
"tryCatchList"                             223.22     97.13      0.00     0.00
"tryCatchOne"                              223.22     97.13      0.00     0.00
"appDependencies"                          209.28     91.06      0.00     0.00
"unique"                                   202.22     87.99      0.76     0.33
"as.vector"                                198.06     86.18      0.14     0.06
"setdiff"                                  197.94     86.13      0.00     0.00
"dirDependencies"                          197.90     86.11      0.00     0.00
"list.files"                               194.90     84.81    194.90    84.81
```

Note that `dirDependencies()` will recursively crawl through files within the packrat project; if this project is on a networked drive it's possible that this is a very slow operation.

Can you replicate the slowness if you call `packrat:::appDependencies()` from the console yourself with this project?

**Comment by raubreywhite** [comment]
Hi,

Sorry for taking so long to get back to you!

Ok, so when I put RStudio into package mode, it takes 4 minutes 18 seconds to run packrat::on()

Outside of package mode, it takes 5 seconds to run packrat::on(). I then ran packrat:::appDependencies() and it took 1 minute. So there is still 3 minutes unaccounted for...

**Comment by raubreywhite** [comment]
I also just created a new RStudio project in a remote directory with nothing in it. Packrat::on() (in project mode) ran pretty much instantaneously. So maybe there is something to do with the number of packages installed by me in my other projects?

**Comment by raubreywhite** [comment]
Ok, I just found out that as long as packrat:::isRPackage()==TRUE, then everything works quickly in project mode. So I'm just going to stick all of my packrat stuff inside my packages. Previously I had:
- Project folder
|-Packrat folder
|-ProjectPackage folder
|-Run.R

By changing my structure to:
- Project folder
|-ProjectPackage folder
|---Packrat folder
|-Run.R

It now runs with no lag :-)

**Comment by UTexas80** [comment]
I am sitting here for the last five hours waiting for my packrat infused project to run. I am utilizing Kenton White's venerable ProjectTemplate for my directory structure. I am hoping that someone can help me understand how I can employ raubreywhite's suggestions from his comment on Apr 20, 2016 to help speed up this process.

In particular, where do I place the 'packrat:::isRPackage()==TRUE,' code. Should it go into the console window or somewhere else? 

Also, here is my folder structure. I do not see which of my folders associate to the ProjectRPackagte folder as cited by raubreywhite.

![projectstructure](https://user-images.githubusercontent.com/16102161/41548093-ee36fb42-72ef-11e8-8057-3ed63e5dd4cf.png)

Any assistance provided is greatly appreciated as I slowly watch the sands of time slip on bye.

Thank you.

**Comment by raubreywhite** [comment]
Hi,

It’s been a loooong time since I wrote this, but looking at my original post I think i remember properly. 

Basically, you need to make an R package using the “devtools::create” function (call it whatever you want, maybe ProjectRPackage). Then you will put your R code inside the ProjectRPackage/R folder. Packrat will live inside ProjectRPackage/packrat, because it will be packrat FOR the R package. You will then have a “Run.R” script living outside this folder, that will be the “brains” that 1) loads in ProjectRPackage, 2) loads in the data, 3) calls the functions to analyse the data.

**Comment by raubreywhite** [comment]
Oh and the “packrat:::isRPackage()==TRUE” code can’t be run by our end. It was just that I noticed when packrat:::isRPackage() was FALSE, it was slow. When packrat:::isRPackage() was TRUE, it was fast. Which led to my R package proposal.

**Comment by UTexas80** [comment]
Thank you so much for the detailed explanation. I am a relative R newbie so I am still scaling that uphill learning curve. Conceptually Packrat seemed like a good option at the time, I just didn't know it was Father Time I was dealing with. The dockers containers seem like the way to go so I will delve into them further. Thanks again.
Glen
