### ISSUE TITLE
cannot read a lock file containing no packages

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#294]
Encountered while trying to test some code which uses `packrat`. I wanted to have a minimal, but still valid `packrat.lock` -- I wanted to make sure my call to `packrat::restore` happened (cheaply).

I tried using this dummy lock file:

```
PackratFormat: 1.4
PackratVersion: 0.4.6.1
RVersion: 3.2.2
Repos: CRAN=https://cran.rstudio.com/
```

Here is what happened:

```
Error in `[.data.frame`(df, , "name") : undefined columns selected
Calls: <Anonymous> ... readLockFile -> deserializePackages -> [ -> [.data.frame
```

**Comment by kevinushey** [comment]
We generally make an assumption that `packrat` is always present as an entry in the lockfile -- that said, this is something we should be able to relax so I'll see what we can do.
