### ISSUE TITLE
Error deploying app to ShinyApps.io

### ISSUE THREAD

**Issue by trestletech** [rstudio/packrat#305]
I get the following error when deploying an app to ShinyApps.io. It looks like the error line is coming in from Packrat, but let me know if you think this should be filed against rsconnect.

```
Preparing to deploy application...DONE
Uploading bundle for application: 24475...Error in vapply(packages, function(pkg) { : values must be length 1,
 but FUN(X[[13]]) result is length 0
Calls: <Anonymous> ... writeLockFile -> lapply -> FUN -> data.frame -> vapply
Execution halted
```

Same result when deploying from rsconnect via CLI and when deploying from the IDE.

The application's code is available here: https://github.com/trestletech/dallas-police/tree/master/shiny

**Comment by kevinushey** [comment]
This was unfortunately a bug in a recent development version of `devtools` (unfortunately resulting from a patch I contributed; the patch has now been rolled back).

The overarching issue is that, for a time, `devtools::install_github()` was not annotating downloaded package `DESCRIPTION` files with the `GithubSHA1` field, and packrat as a result no longer understood how to restore those packages.

You can rectify this by installing the latest development version of `devtools`: 

    devtools::install_github('hadley/devtools')

and then run this script to identify any packages that need to be reinstalled:

```R
fmt <- "Package '%s' is missing the GithubSHA1 field and needs to be reinstalled."
pkgDirs <- list.files(.libPaths(), full.names = TRUE)
descPaths <- file.path(pkgDirs, "DESCRIPTION")
pkgInfo <- lapply(descPaths, function(path) {
  tryCatch({
    pkg <- basename(dirname(path))
    contents <- readChar(path, file.info(path)$size, TRUE)
    Encoding(contents) <- "UTF-8"
    if (grepl("GithubRepo", contents) && !grepl("GithubSHA1", contents)) {
      cat(sprintf(fmt, pkg), sep = "\n")
      return(pkg)
    }
    NULL
  }, error = function(e) NULL)
})

needsReinstall <- as.character(Filter(Negate(is.null), pkgInfo))
if (length(needsReinstall) == 0) {
  cat("All packages appear up to date -- no action necessary.")
} else {
  cat("One ore more packages need to be updated.")
}
```

Depending on how many other people this affects in the wild we might need to either announce it or better diagnose the error in packrat. Sorry for the trouble :/

**Comment by trestletech** [comment]
Worked like a charm! Thanks.
