### ISSUE TITLE
packrat fails to init if "malformed" yaml in Rmd

### ISSUE THREAD

**Issue by antoine-sachet** [rstudio/packrat#312]
To reproduce:
- Create a new project without packrat
- Create a Rmd file with malformed yaml, for example here the date is dynamic:

```

---
title: "Minimal Reproducible Example"
author: "antoine-sac"
date: `r format(Sys.Date(), '%d %B %Y')`
output: html_document

---

This is an R Markdown document.

```
- Why not add a R file with some library calls. This is how the Rmd file is processed. It works perfectly well BTW.

```
library("rmarkdown")
library("knitr")

knit("test.Rmd")
render("test.md")

```
- Now try packrat::init()

This fails with error:

> Error in yaml::yaml.load(enc2utf8(string), ...) : 
>   Scanner error: while scanning for the next token at line 3, column 7found character that cannot start any token at line 3, column 7

Can this be fixed? Why is packrat parsing the yaml at all?
Or can we add a way to specify that only R files should be scanned (effectively discarding Rmd files during scanning)?

**Comment by kevinushey** [comment]
Packrat parses the YAML to ascertain package dependencies; e.g. to infer whether an `rmarkdown` document needs `shiny`, or calls into an R function specified by another R package, and so on.

I think we can definitely change this to be a warning rather than an error, though.

We could / should also make the dependency discovery more configurable, as well.

**Comment by antoine-sachet** [comment]
Thanks Kevin, this is a simple and effective fix. Although this is very bad from a "desensitization to warnings" point of view ;)

**Comment by teyden** [comment]
I still have issues related to "malformed" yaml configuration, while the RMD files knit without errors. The knitr and packrat versions I'm using are up to date. 

Any idea why this might be happening? The errors I get when trying to initialize packrat are:

```
Error in yaml::yaml.load(..., eval.expr = TRUE) : 
  Scanner error: mapping values are not allowed in this context at line 8, column 8
```

**Comment by kevinushey** [comment]
@teyden it most likely implies that some R Markdown document in your project (unfortunately, it's hard to know which one currently) does have some kind of error in its YAML header.

Your best hope is to try something like:

```
options(error = recover)
```

and see if the R debugger can tell you which file's YAML header is being read, and why that is failing.
