### ISSUE TITLE
Packages not cached if one fails

### ISSUE THREAD

**Issue by trestletech** [rstudio/packrat#324]
I've had a few instances in which the first 10 packages build successfully and take quite a while but some later package fails. Once I resolve the issue that caused the later package to fail I have to start all over again and rebuild the first 10 packages.

Is there a reason we don't add packages to the cache as they successfully build rather than waiting until the end?

**Comment by kevinushey** [comment]
I don't think there's any reason in particular -- this is definitely something worth looking at.

**Comment by kevinushey** [comment]
Should be good to go now!
