### ISSUE TITLE
Make Travis-CI detect and use packrat packages when building a package

### ISSUE THREAD

**Issue by benmarwick** [rstudio/packrat#330]
When we make an R project or R package we sometimes want to include the source files of the R packages we depend on, to prevent changes in other packages breaking our code. 

How can we configure travis to install these packages from the source included in the local project, rather than download from CRAN?

I'm working with an R package that is an RStudio project, and I'm using packrat to keep a local copy of the source of the packages I depend on for my project.

I've got Travis-CI checking my R package each time I make a commit, but each time Travis builds my package it gets the latest version of the dependent packages, rather than the versions I've got in my packrat/ directory.

I can see in @richfitz's [wood](https://github.com/richfitz/wood/) that he appears to have achieved this goal with this in his .travis.yml file:

```
env:
 USE_PACKRAT=1
```
and a fairly complex [make/packrat.mk](https://github.com/richfitz/wood/blob/master/make/packrat.mk) file which makes it all work.

My question is what is the simplest way to configure my project (e.g. my .travis.yml file) to tell the Travis machine to get the packages from my `packrat/` directory on github, and not from CRAN?

I have cross-posted this question on [SO](http://stackoverflow.com/questions/39009579/using-r-package-source-files-in-packrat-rather-than-cran-with-travis-ci), the [rOpenSci list](https://discuss.ropensci.org/t/reproducibility-in-r-package-building-with-travis-and-packrat/445), and the [Travis-CI issue tracker](https://github.com/travis-ci/travis-ci/issues/6504). There have been no replies anywhere so far :$

**Comment by kevinushey** [comment]
IIUC, this was resolved by using `--bootstrap-packrat` when launching the R session? This seems like the right way to go to me as well.

**Comment by benmarwick** [comment]
Thanks, yes I just came across that yesterday and documented my results here: http://stackoverflow.com/a/39338706/1036500

In brief, this works great in the `travis/yml`

```
install:
  - R -e "0" --args --bootstrap-packrat
```

but there is a big increase in build time because there doesn't seem to be any caching of packages built from sources stored by packrat.

**Comment by kevinushey** [comment]
That's indeed one of the big downsides. I know Travis does some caching, but that may be only for current CRAN versions of R packages -- I don't know if there's a way to force caching from user-defined `.travis.yml` scripts.

**Comment by henningsway** [comment]
I'm currently looking for a way to decrease the build time of my packrat project on travis.

Are there any new options available, that would help cache the building of the sources?
