### ISSUE TITLE
copies into cache need to first land in temporary location

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#333]
`moveInstalledPackageToCache` copies a package from its initial install location to its final position in the packrat cache. This copy is performed to the actual destination. This means that we may leave a partial, but not obviously incomplete directory should that copy err for some reason or get interrupted.

https://github.com/rstudio/packrat/blob/5085b60109edfdd5f70292413f2f1ccc7878a590/R/cache.R#L139

We should first copy to a temporary location (inside the same directory) and then perform a rename operation. Using the same parent directory ensures that we are on the same mounted device and the rename ensures that we will not accidentally see the package as already installed.

**Comment by kevinushey** [comment]
Should be resolved now; thanks!
