### ISSUE TITLE
support for GitHub redirects

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#336]
See https://github.com/rstudio/flexdashboard/issues/96

**Comment by kevinushey** [comment]
Packrat should already support this. Can you provide a reproducible example?

**Comment by aronatkins** [comment]
Yeah. I don't have sufficient information; I was just trying to extract the issue from flexdashboard.

**Comment by aronatkins** [comment]
Never got sufficient details to understand the issue.
