### ISSUE TITLE
formatR required to click knit in Rstudio, but it's not a dependency

### ISSUE THREAD

**Issue by rubenarslan** [rstudio/packrat#354]
I think packrat understands that yaml, rmarkdown and knitr are present.

But if you click Knit in the RStudio IDE, it also wants to install `formatR`.
This annoys me a bit when using packrat, because it will never install `formatR` unless I explicitly specify and will remove it unless I do some monkey business like 

```r
# some packages may be needed without being loaded
fool_packrat = function() {
	library(devtools) # needed to install formr package
	library(formatR) # needed to actually run rmarkdown in RStudio, but for some reason not in its dependencies
}
```

Sorry, if this is the wrong place to report this issue, don't really know a better place.

**Comment by kevinushey** [comment]
Thanks for spotting this! This is an issue in the RStudio IDE itself; I'll see if we can get it fixed there.
