### ISSUE TITLE
Install package from github repo?

### ISSUE THREAD

**Issue by inkrement** [rstudio/packrat#362]
How can I properly install github-packages a la `devtools::github_install()`? `packrat::install_github("rstudio/rmarkdown")` is used in the documentation (https://rstudio.github.io/packrat/rstudio.html), but it seems like it is not supported:

> $ packrat::install_github("rstudio/rmarkdown")
> Error: 'install_github' is not an exported object from 'namespace:packrat'

> $ packrat:::install_github("rstudio/rmarkdown")
> Error in get(name, envir = asNamespace(pkg), inherits = FALSE) : 
>  object 'install_github' not found

RStudio 1.0.136, packrat 0.4.8-1

**Comment by kevinushey** [comment]
We originally had our own wrapper over `install_github()`, but in the end decided that this was too error-prone (especially since it didn't handle e.g. private GitHub repositories) so we decided to just request users call `devtools::install_github()` directly.

**Comment by inkrement** [comment]
Ok thanks, this makes sense! But please update the documentation, it is quite confusing.

**Comment by Adam-Hoelscher** [comment]
Echoing @inkrement that the documentation needs an update, and a related question.

I don't need `devtools` for my project code to function, only to load other packages which my project does need to function. When packrat is turned on, `devtools` isn't in my search path, so I can't run `devtools::install_github`. When packrat is turned off, I can run `devtools::install_github`, but the lib then doesn't default to packrat. What's the intended workflow here?

**Comment by actuarialvoodoo** [comment]
Hi @Adam-Hoelscher Not sure if you ever resolved this problem, but what I've done is to put devtools in list of external packages so it's available to my packrat project but not part of the library or dependencies.

**Comment by jolars** [comment]
You can also use `with_extlib()`, like so: 

```r
packrat::with_extlib("devtools", install_github("jolars/SLOPE"))
```

**Comment by hreypar** [comment]
> You can also use `with_extlib()`, like so:
> 
> ```r
> packrat::with_extlib("devtools", install_github("jolars/SLOPE"))
> ```

THANK YOU

**Comment by hreypar** [comment]
> You can also use `with_extlib()`, like so:
> 
> ```r
> packrat::with_extlib("devtools", install_github("jolars/SLOPE"))
> ```

I found that to use this option I had to specify `lib` within `install_github`  (and use `packrat/lib/`)
