### ISSUE TITLE
yaml header with 'params' --> `Unable to tagle file`

### ISSUE THREAD

**Issue by r-cheologist** [rstudio/packrat#375]
I have a `bookdown` project where a `yaml` header contains

    params:
      short: false

which is a custom parameter I use to compile two different variations of the same report from one source. `Packrat` is unable to gracefully deal with this and when I hit "Check for package updates", it reports:

    Unable to tangle file '<MYFILE>.rmd'; cannot parse dependencies
    Error in eval(x, envir = envir) : object 'params' not found

Sincerely, Joh

**Comment by colearendt** [comment]
Related to #363 ?

**Comment by saverygomm** [comment]
Any progress on this issue? Getting set up with packrat (for the first time). Encountered 

'Unable to tangle file '/Users/......./NOFU-Labrador-Sea-Plastic-Baseline5_Total-Mass-Plastic-g.Rmd'; cannot parse dependencies 

when I used packrat::snapshot(). 

    RStudio Version 1.0.153
    R version 3.4.1 (2017-06-30)
    Platform: x86_64-apple-darwin15.6.0 (64-bit)
    Running under: macOS Sierra 10.12.5
    packrat_0.4.8-1

Link to issue #363 didn't help me...

Many thanks, 
Stephanie

**Comment by kevinushey** [comment]
I can't reproduce the issue as described. I can successfully tangle this file:

```
---
title: "Untitled"
output: html_document
params:
  short: false
---

# Hello, world!
```

Can you provide a reproducible example?
