### ISSUE TITLE
Unable to initialize packrat in project with dependency on XML package

### ISSUE THREAD

**Issue by BroVic** [rstudio/packrat#380]
Hi,

I've tried, to no avail, to run `packrat::init()` in a project of mine that has a dependency on the old XML package. Whenever it gets to the point of installing XML it stops. This is the console output I receive:

```
Error: Command failed (1)

Failed to run system command:

	"C:/PROGRA~1/R/R-33~1.3/bin/x64/R" --vanilla CMD INSTALL "C:\Users\Admn\AppData\Local\Temp\Rtmp61775Q\XML" --library="C:/Users/Admn/Documents/7-NESREA/SA/WMG/NESREA_social/packrat/lib/x86_64-w64-mingw32/3.3.3" --install-tests --no-docs --no-multiarch --no-demo 

The command failed with output:
* installing *source* package 'XML' ...
** package 'XML' successfully unpacked and MD5 sums checked
** libs
c:/Rtools/mingw_64/bin/gcc  -I"C:/PROGRA~1/R/R-33~1.3/include" -DNDEBUG -I/include/libxml2 -I/include -D_R_=1 -DUSE_R=1 -DUSE_XML_VERSION_H=1 -DLIBXML -DUSE_EXTERNAL_SUBSET=1 -DROOT_HAS_DTD_NODE=1 -DUMP_WITH_ENCODING=1 -DXML_ELEMENT_ETYPE=1  -DXML_ATTRIBUTE_ATYPE=1 -DLIBXML2=1 -DHAVE_XML_HAS_FEATURE -DLIBXML_STATIC    -I"d:/Compiler/gcc-4.9.3/local330/include"     -O2 -Wall  -std=gnu99 -mtune=core2 -c DocParse.c -o DocParse.o
In file included from DocParse.c:10:0:
DocParse.h:18:27: fatal error: libxml/parser.h: No such file or dire
```
I noticed that libxml2 is a system requirement for the installation of the R 'XML' package.
I have tried downloading and installing libxml2 and even tried extracting include/libxml2 to a folder on the GCC search path. 

My R Session:
```
R version 3.3.3 (2017-03-06)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

locale:
[1] LC_COLLATE=English_United Kingdom.1252 
[2] LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252
[4] LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] packrat_0.4.8-1

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.7         digest_0.6.12       rprojroot_1.2      
 [4] assertthat_0.1      grid_3.3.3          plyr_1.8.4         
 [7] gtable_0.2.0        backports_1.0.5     formatR_1.4        
[10] magrittr_1.5        evaluate_0.9        scales_0.4.1       
[13] ggplot2_2.2.1       stringi_1.1.2       lazyeval_0.2.0     
[16] myRstuff_0.0.0.9000 rmarkdown_1.3       tools_3.3.3        
[19] stringr_1.2.0       munsell_0.4.3       yaml_2.1.13        
[22] colorspace_1.2-6    htmltools_0.3.5     knitr_1.14         
[25] tibble_1.2 
```

**Comment by kevinushey** [comment]
The XML package sources include this in a `README.windows` file:

```
You can use install.packages() to install this package, but to use it
in R, you will have to add the XML/libs directory to your path or copy
the files

  libxml2.dll zlib.dll iconv.dll

to a directory in your path.  Putting them into the directory which
contains Rgui.exe and Rterm.exe for this version of R is probably
best.  They will hopefully not interfere with other applications
that rely on alternate versions.


=====================================================================


COMPILING the PACKAGE
---------------------

To compile this package on a Windows machine is quite easy.  Since the
package depends on libxml (version 2), you will have to get the
development version of that package for compiling with MingGW.  To do
this, I have followed the links from www.xmlsloft.org to

   http://www.zlatkovic.com/libxml.en.html 

(The libraries are available directly at http://www.zlatkovic.com/pub/libxml/ )

From the "Getting the Binaries" section, download the zlib, iconv,
libxml2 (and openssl) zip files.

Having fetched these binaries, I unzip these and move the relevant
files to a common area.  Specifically, in my HOME directory on the
cygwin setup on Windows, I create the following directories:

  include/
  lib/
  bin/

Then I copy the files from each of these directories in the .zip files 
to these directories. 


Now, all we need to do is tell the GNU make utility where to find
these header and library files.  You can either edit the
src/Makevars.win file and specify a value for (the now misnamed)
LIB_XML variable to the directory containing the include/, lib/ and
bin/ directory created earlier. In my case, this is $HOME, but
specified as

  D:/cygwin/home/duncan

(rather than /home/duncan).
The remainder of the file should not need to be modified.

Alternatively, you can specify this as an environment variable, e.g.
  export LIBM_XML=D:/cygwin/home/duncan
 

To create a binary, I copy libxml2.dll, iconv.dll and zlib.dll to the
directory XML/inst/libs in the source and then run

  Rcmd build --binary XML
```

which unfortunately seems to suggest that installation from sources on Windows is somewhat convoluted.

**Comment by BroVic** [comment]
Thanks a lot. Will take a breather first and revert when I've implemented this.

**Comment by BroVic** [comment]
When I got back to working on this, I followed the steps recommended in the above file, but didn't get further. I noticed that the 64-bit version I was using was named libxml2-2.dll, and further research led me to the section [**Using Makevars**](https://cran.r-project.org/doc/manuals/r-release/R-exts.html#Using-Makevars) in "_Writing R Exrtensions_" that alluded to this problem. Happily, though, and I hope this eventually makes me happy, I found that a [**new version of XML**](https://cran.r-project.org/web/packages/XML/index.html) was released just yesterday. I've looked at the documentation and see that there's a lot of new stuff about cooking it for Windows. I will give it a go in the coming days. Again thanks for your help thus far.

**Comment by BroVic** [comment]
Okay, I am yet to sort this out. For the time being I did a `packrat::set_opts(external.packages = "XML")`, since I already have the package installed in the default User library, and so that I can move ahead with my work. I will keep trying at my leisure.

**Comment by kevinushey** [comment]
Packrat definitely needs a better story for Windows packages in particular, since installing from source for many packages is simply untenable. Glad you were able to find a workaround but wish we had a cleaner path forward on the Packrat side :/

**Comment by MarkusBonsch** [comment]
Can't one resort to installing binaries with packrat? Adding an option `install.type` with "source", and "binary" similar to the install.packages option? I can maybe help implementing this as my time allows.

**Comment by kevinushey** [comment]
Packrat does attempt to install binaries, but only if the version of the package in the lockfile is current and binaries for it are already available on CRAN.

In other words, Packrat won't auto-update to the current binary version of a package on CRAN -- the onus is on the user to manually install new binaries, and then re-snapshot to pick up the changed dependencies.

**Comment by MarkusBonsch** [comment]
Thank you for the clarification.

**Comment by aonurdemir** [comment]
Upgrading failing package version made my day :)
