### ISSUE TITLE
Problem when using packrat::init() for a Shiny project

### ISSUE THREAD

**Issue by philstraforelli** [rstudio/packrat#383]
I'm running into an issue when I'm trying to follow the direction of this article: https://support.rstudio.com/hc/en-us/articles/216528108-Deploying-packrat-projects-to-Shiny-Server-Pro

I run the following command (I have saved my files specific to the shiny dashboard in its own folder within my project folder):

    packrat::init(paste0(getwd(), "/shinydashboard/"))

And I get the following prompt:

    Initializing packrat project in directory:
    - "~/Projects/projectname/shinydashboard"
    Fetching sources for glue (1.1.1) ... OK (CRAN current)
    Snapshot written to "C:/Users/PStraforelli/Documents/Projects/projectname/shinydashboard/packrat/packrat.lock"
    Installing glue (1.1.1) ... 
    y/n:

If I enter "y" I get the following error:

    Error in hash(descFile) : 
      No DESCRIPTION file at path 'C:/Users/PStraforelli/Documents/Projects/projectname/shinydashboard//packrat/lib/x86_64-w64-mingw32/3.4.0/glue/DESCRIPTION'!
    In addition: Warning messages:
    1: running command '"C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R" CMD INSTALL -l "C:\Users\PStraforelli\Documents\Projects\projectname\shinydashboard\packrat\lib\x86_64-w64-mingw32\3.4.0" C:\Users\PSTRAF~1\AppData\Local\Temp\Rtmpk77Yxl/downloaded_packages/glue_1.1.1.tar.gz' had status 1 
    2: In utils::install.packages(pkgRecord$name, lib = lib, repos = repos,  :
      installation of package ‘glue’ had non-zero exit status

If I try again and enter "n" this time it completes the process. When I attempt the following line from the article:

    packrat::snapshot()

I get the following response:

    The following packages are stale:
         _      
    glue   1.1.0

    These packages must be updated by calling packrat::restore() before
    snapshotting. If you are sure you want the installed versions of these
    packages to be snapshotted, call packrat::snapshot() again with
    ignore.stale=TRUE.
    --
    Snapshot operation was cancelled, no changes were made.

I'm not sure what's causing this. My computer has version 1.1.1 of `glue` so why is it telling me it has 1.1.0?

**Comment by kevinushey** [comment]
It looks like installation is failing for some reason, as per your build output:

```
In addition: Warning messages:
1: running command '"C:/PROGRA~1/R/R-34~1.0PA/bin/x64/R" CMD INSTALL -l "C:\Users\PStraforelli\Documents\Projects\projectname\shinydashboard\packrat\lib\x86_64-w64-mingw32\3.4.0" C:\Users\PSTRAF~1\AppData\Local\Temp\Rtmpk77Yxl/downloaded_packages/glue_1.1.1.tar.gz' had status 1 
2: In utils::install.packages(pkgRecord$name, lib = lib, repos = repos,  :
  installation of package ‘glue’ had non-zero exit status
```

It looks as though Packrat is attempting to install the package from source, even though it should be attempting to download and install a binary here. If the source install is failing, that's likely because you don't have [Rtools](https://cran.r-project.org/bin/windows/Rtools/) installed.

**Comment by kevinushey** [comment]
You might also want to make sure you're using the development version of Packrat, as a number of tweaks + bug fixes have been made:

    devtools::install_github("rstudio/packrat")

**Comment by philstraforelli** [comment]
Thanks for responding, Kevin. I do have Rtools installed.
![capture](https://user-images.githubusercontent.com/22040238/27446555-d26fafb4-5732-11e7-8326-ea8cba866450.PNG)

I'll attempt with the development version.

**Comment by kevinushey** [comment]
What do you see if you try to install the package directly from R with a plain old

    install.packages("glue", type = "source")

Does that work as expected?

**Comment by philstraforelli** [comment]
This works as expected. I've also re-installed Rtools, and ran `devtools::find_rtools()` to ensure it functions properly. It returned TRUE. 

I've re-run the `packrat::init()` command and I'm still getting the same issue.

**Comment by philstraforelli** [comment]
I've attempted to run this again today, and it now works fine. I have no idea why my machine is behaving today but not yesterday. Either way, this was evidently an issue on my end and not a bug with `packrat`, so we can close this issue.
