### ISSUE TITLE
Can't install CRAN package when there is a more recent version in an additional repo.

### ISSUE THREAD

**Issue by jwg4** [rstudio/packrat#389]
I was having a lot of problems running `packrat::init()` in our project which has several different dependencies from outside of CRAN. It seemed that there was a mismatch between the repos that packrat checks when it decides which versions to install, and the places it tries to download those packages from.

Minimal example:
A directory with a single file, hello.R
```
library(xts)
```
R session in that directory:
```
R version 3.4.0 (2017-04-21) -- "You Stupid Darkness"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-pc-linux-gnu (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> local({r <- getOption("repos"); r["EXTRA"] <- "http://R-Forge.R-project.org/"; options(repos=r)})
> packrat::init()
Initializing packrat project in directory:
- "~/z"

Adding these packages to packrat:
            _        
    packrat   0.4.8-1
    xts       0.9-7  
    zoo       1.8-0  

Fetching sources for packrat (0.4.8-1) ... OK (CRAN current)
Fetching sources for xts (0.9-7) ... OK (CRAN archived)
Fetching sources for zoo (1.8-0) ... curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
curl: (22) The requested URL returned error: 404 Not Found
FAILED
Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to retrieve package sources for zoo 1.8-0 from CRAN (internet connectivity issue?) [1.8-1 is current]
```

If I have understood this correctly, `available.packages()` doesn't take R-forge into account when deciding which package to install. However, it then tries to download the package versions it has obtained from CRAN, from R-forge. I didn't include it in the example, but my real project depends on a package which is only available on R-forge, which is why I changed the repo options.

Is this a packrat bug? Or am I going about this the wrong way?

**Comment by jwg4** [comment]
Having done some more research, it seems I'm not right about available.packages() being the culprit.

**Comment by kevinushey** [comment]
What's the output of `getOption("repos")` in your project?

When downloading R packages, Packrat will first attempt to see if that package is available currently on CRAN; if not, it will ping Archive links for each of the listed repositories in the `"repos"` option. That's where the extra noise from 

    curl: (22) The requested URL returned error: 404 Not Found

is presumedly from; FWIW we should be suppressing those warnings in the development version of Packrat.

**Comment by jwg4** [comment]
I don't think those messages are just noise. The whole process fails with
```
Error in snapshotSources(project, activeRepos(project), allRecordsFlat) : 
  Errors occurred when fetching source files:
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to retrieve package sources for zoo 1.8-0 from CRAN (internet connectivity issue?) [1.8-1 is current]
```
so it looks like the 404 errors cause this.

**Comment by kevinushey** [comment]
What's the output of getOption("repos") in your project?

**Comment by jwg4** [comment]
@kevinushey I explicitly update the `repos` option in the code I pasted above. This shows the value on startup and the value after I change it:
```
> getOption("repos")
    CRAN 
"@CRAN@" 
> local({r <- getOption("repos"); r["EXTRA"] <- "http://R-Forge.R-project.org/"; options(repos=r)})
> getOption("repos")
                           CRAN                           EXTRA 
                       "@CRAN@" "http://R-Forge.R-project.org/" 
```

**Comment by jwg4** [comment]
I can confirm that this works with the development version installed from github.
