### ISSUE TITLE
Dependencies not available for package

### ISSUE THREAD

**Issue by AkhilNairAmey** [rstudio/packrat#391]
Hi,

I think I might be unsure of the workflow `packrat` expects.  

I'm trying to make a docker image using `packrat` for dependencies management.  As a simple example, I've:
 - Created a completely new project
 - Ran
   -  `packrat::on()`
   - `install.packages("RSQLite")`
   - `packrat::snapshot()`
 - To the emulate the docker environment, I deleted all the `packrat/lib*` folder and `src`, as I would add these to the `.dockerignore`, as all the package information needed is in the `packrat.lock` file
 - Then running `packrat::restore()` I hit the error:

```
> packrat::restore()
Installing BH (1.62.0-1) ... 
	OK (built source)
Installing DBI (0.7) ... 
	OK (built source)
Installing RSQLite (2.0) ... 
Error: Command failed (1)

Failed to run system command:

	'/usr/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmppGgJVt/RSQLite' --library='/home/akhil/example/packrat/packrat/lib/x86_64-pc-linux-gnu/3.3.3' --install-tests --no-docs --no-multiarch --no-demo 

The command failed with output:
ERROR: dependencies 'bit64', 'blob' are not available for package 'RSQLite'
* removing '/home/akhil/example/packrat/packrat/lib/x86_64-pc-linux-gnu/3.3.3/RSQLite'
```

Slightly confused at what I should do at this point - `bit64` and `blob` are in the `lock` file, but I don't know how to tell packrat to install the dependencies first. 

I get the same result using `packrat::bundle()` and `packrat::unbundle(..., restore = TRUE)` (which, from what I can see, does the same as I was doing, just keeping the `packrat/src/` folder)

I've also asked this question on stackoverflow [here](https://stackoverflow.com/questions/45264733/packrat-dependencies-unavailable).

**Comment by AkhilNairAmey** [comment]
Just seen that my problem is the same as in #373, however I'm having trouble making the `Requires:` field exist in the lock file...

**Comment by kevinushey** [comment]
Are you using the development version of Packrat? Interestingly, I see the same issue (the `Requires:` fields are not populated in the DESCRIPTION file) but installation still seems to succeed. I'll try to investigate further.

**Comment by AkhilNairAmey** [comment]
I am, yep:

```
> Using user-library packrat (0.4.8.21) to bootstrap this project
```

Thanks!

**Comment by kevinushey** [comment]
It looks like this was indeed a regression -- should be fixed in the latest development version of Packrat (0.4.8.22). Can you give it a shot and let me know if it appears fixed on your side?

**Comment by AkhilNairAmey** [comment]
@kevinushey Work great - Thanks!

Shedding a tear for the time I spent writing in those dependencies :'(

**Comment by kevinushey** [comment]
:) Phew, glad to hear it! Sorry for the trouble in the first place; thanks for taking the time to provide a reproducible example -- it makes fixing these kinds of issues much easier!
