### ISSUE TITLE
packrat::restore doesn't search local repos

### ISSUE THREAD

**Issue by umayrnuna** [rstudio/packrat#393]
Hi,

We, at Nuna Health, use Packrat extensively for managing R projects. We do wish there was more extensive documentation but we're grateful for a very powerful package.

We have local R packages that depend on other local packages (i.e. apart from CRAN dependencies). It seems that Packrat is unable to restore such a package during packrat::init() since it cannot infer the package dependencies' locations, and assumes that all dependencies are available on CRAN. I think the TODO in https://github.com/rstudio/packrat/blob/e5c87eae01175de1b90f7ae0b74ec573e49ebc62/R/restore.R#L57 indicates that.

When do you think this TODO would be resolved? Can we help in anyway - perhaps with a pull request?

**Comment by kevinushey** [comment]
Unfortunately, Packrat's notion of 'local repositories' (that is, a directory full of package sources) was a bit misguided, and I think should be considered soft-deprecated at this point.

What you might try instead is setting up a custom CRAN-like repository, as per the instructions in https://rstudio.github.io/packrat/custom-repos.html. This does imply a bit more work up-front on the user side, but I think it's ultimately worth it.

**Comment by umayrnuna** [comment]
Thanks!
