### ISSUE TITLE
packrat::restore() fails to restore when src version > bin version

### ISSUE THREAD

**Issue by shiosai** [rstudio/packrat#398]
The following situation happens quite often. Currently its happening with caret:
**packrat.lock**
`Package: caret
Source: CRAN
Version: 6.0-77`

**On CRAN**
Packrat SRC: caret_6.0-**77**.tar.gz
Packrat BIN WIN: r-release: caret_6.0-**76**.zip

```
> packrat::restore()
Installing caret (6.0-77) ... 
FAILED
Error in getSourceForPkgRecord(pkgRecord, srcDir(project), availablePkgs,  : 
  Failed to retrieve package sources for caret 6.0-77 from CRAN (internet connectivity issue?) [6.0-76 is current]
In addition: Warning message:
In getSourceForPkgRecord(pkgRecord, srcDir(project), availablePkgs,  :
  Package version '%s' is newer than the latest version reported by CRAN ('%s') -- packrat may be unable to retrieve package sources.
```

I had a short debug session and because of the version difference it wants to download 6.0.77 src from the archive - which doesnt exist there yet of course:
`archiveURL: http://cran.rstudio.com//src/contrib/Archive/caret/caret_6.0-77.tar.gz`

**Comment by kevinushey** [comment]
Thanks for the bug report! I believe this particular issue is resolved in the development version of packrat -- can you download that and let me know if that rings true for you?

```R
devtools::install_github("rstudio/packrat")
```

**Comment by shiosai** [comment]
Hi.. yes it works now!
There is still an issue with snapshot though when using the outdated caret version (I tested that as workaround):
`Package: caret Source: CRAN Version: 6.0-76`

```
Fetching sources for caret (6.0-76) ... FAILED
Error in getSourceForPkgRecord(pkgRecord, sourceDir, availablePkgs, repos) : 
  Failed to retrieve package sources for caret 6.0-76 from CRAN (internet connectivity issue?) [6.0-77 is current]
```

I didn't debug this time but probably it expects the srcs to be next to the outdated windows bin and not in the archives?

CARET is just one example again.. i have this issue with rstudio api as well (0.6 -> 0.7)

**Comment by kevinushey** [comment]
Interesting, thanks -- I'll try to investigate further. It looks like that version of caret does indeed exist in the archive (at least for the RStudio CRAN mirror) at

https://cran.rstudio.com/src/contrib/Archive/caret/caret_6.0-76.tar.gz

so I'll have to see what's going on.

**Comment by kevinushey** [comment]
This worked fine for me with `rstudioapi` -- I can restore a project regardless of whether it's using 0.7 or 0.6.

Can you provide the output of `sessionInfo()` and `getOption("pkgType")`?

**Comment by shiosai** [comment]
With windows as well? I can try to step through my run to figure out where it fails
```
> sessionInfo()
R version 3.4.1 (2017-06-30)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows 7 x64 (build 7601) Service Pack 1

Matrix products: default

locale:
[1] LC_COLLATE=German_Germany.1252  LC_CTYPE=German_Germany.1252    LC_MONETARY=German_Germany.1252
[4] LC_NUMERIC=C                    LC_TIME=German_Germany.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] packrat_0.4.8-37

loaded via a namespace (and not attached):
 [1] Rcpp_0.12.12     codetools_0.2-15 digest_0.6.12    withr_2.0.0      rprojroot_1.2    R6_2.2.2         backports_1.1.0 
 [8] git2r_0.19.0     magrittr_1.5     evaluate_0.10.1  httr_1.3.1       stringi_1.1.5    curl_2.8.1       rmarkdown_1.6   
[15] devtools_1.13.3  tools_3.4.1      stringr_1.2.0    yaml_2.1.14      compiler_3.4.1   memoise_1.1.0    htmltools_0.3.6 
[22] knitr_1.17 
```

```
> getOption("pkgType")
[1] "win.binary"
```

**Comment by shiosai** [comment]
I stepped through the code and the pathes were fine - it attempted to download the correct archive file but eventually stopped with an error in **downloadImpl**:

```
Error: 'seti2' is defunct.
See help("Defunct")
```
Apparently this is the case since R3.3. Checking the code it seems, there is a workaround with "wininet" in the secureDownloadMethod but not the downloadImpl which was used in my case because I use a http repo (as there were authorization issues on some machines). Perhaps the workaround has just to be added to the downloadImpl method as well?
