### ISSUE TITLE
bundle: don't bundle .Rhistory

### ISSUE THREAD

**Issue by ClaytonJY** [rstudio/packrat#401]
That `packrat::bundle` includes `.Rhistory` seems like very unexpected behavior; command history is generally treated as personal information and should not be shared, or at least not by default.

Could `packrat::bundle()` exclude `.Rhistory` files, or at least exclude them by default with an argument like `include.rhistory = FALSE`?

**Comment by kevinushey** [comment]
Good idea! I agree 100% we shouldn't bundle this by default.
