### ISSUE TITLE
Packrat init or snapshot failing to retrieve sources with Packrat 0.4.8-41

### ISSUE THREAD

**Issue by rspreafico** [rstudio/packrat#403]
Hi, restoring a Packrat library from an existing project works. But upgrading packages and then `snapshot` or `init` (after deleting `.Rprofile` and the `packrat` folder and restarting) fails to retrieve the sources. 

I have tried both the HTTP and HTTPS repos for both CRAN and Bioconductor, I have tried `curl`, `libcurl` and `internal` for `options(download.file.method)`, and I have tried both R 3.2.3 and 3.4.1. 

With Packrat 0.4.8-1 everything works, but not with the latest Packrat 0.4.8-41.

**Comment by kevinushey** [comment]
What output are you seeing after attempting to call `packrat::snapshot()`?

**Comment by rspreafico** [comment]
It tries to download packages, but it invariably ends up with "FAILED" for each one, that tries with the next package, FAILED again, etc. This is independent of the download method. Certain download methods, such as curl, are more verbose, returning a 404 error for multiple attempts (I have configured both CRAN and Bioconductor repositories).

**Comment by kevinushey** [comment]
If I understand correctly, you're seeing the failure during package install, not during package download?

Can you also provide the output of `utils::sessionInfo()`?

**Comment by rspreafico** [comment]
Now 0.4.8-47 works

**Comment by rspreafico** [comment]
No longer relevant with new releases.
