### ISSUE TITLE
Packrat should log network errors more usefully

### ISSUE THREAD

**Issue by scottmmjackson** [rstudio/packrat#404]
`Error in fileLoc[1, 2]: subscript out of bounds` is an error that's returned when network instability prevents `packrat::restore` from completing. It should be changed to reflect the fact that `download.packages` failed due to network instability.

**Comment by aronatkins** [comment]
Similar to https://github.com/rstudio/packrat/issues/201

**Comment by aronatkins** [comment]
https://github.com/rstudio/packrat/issues/111 hit the same error (`fileLoc`)

**Comment by aronatkins** [comment]
I think it is hilarious that this issue ended up #404. Surely, there's a better HTTP code? 😜
