### ISSUE TITLE
Setting up reparse point in network drive

### ISSUE THREAD

**Issue by JauntyJJS** [rstudio/packrat#405]
Hi,

I have installed R3.4.1 into the C drive and install the packrat library in there as well.
When I typed packrat::init() on a working directory that is not C:/ or D:/, packrat seems to give a warning that it is unable to set reparse point

Here are some pictures.
It works ok in D drive

![ddrive_example](https://user-images.githubusercontent.com/9066508/31158110-f1013dce-a8f1-11e7-824d-6388bc8a4eed.png)

For a H drive mounted network path (to \\\\fs5\stfhome\)

![image](https://user-images.githubusercontent.com/9066508/31158134-2a598612-a8f2-11e7-9451-4c3c730a1a36.png)

For a \\\\{network name path} (e.g \\\\hornbill\{some path}
![image](https://user-images.githubusercontent.com/9066508/31158177-81f88d3c-a8f2-11e7-9318-10c3ea1c42ce.png)

The same warning also appears in Visual Studio as well.
Should I worry about this warning ?
Please advise. Thank you.

Regards,
Jeremy

**Comment by kalibera** [comment]
Responded to a report of the same issue at R-devel a few minutes ago: junctions cannot link to a network drive, this is a limitation in Windows, junctions can only link directories on the same computer (possibly on different local volumes).

**Comment by JauntyJJS** [comment]
Understood.
