### ISSUE TITLE
packrat::init() results in Warning after installing newest Rstudio version

### ISSUE THREAD

**Issue by hugeme** [rstudio/packrat#417]
Initiating packrat either via packrat::init() or via Rstudio results in:

    R> packrat::init(options = list(auto.snapshot = TRUE))
    Initializing packrat project in directory:
    - "~/dir/myproject"
    Warning: unable to access index for repository https://cran.uni-muenster.de/src/contrib:
      cannot open URL 'https://cran.uni-muenster.de/src/contrib/PACKAGES'

    Adding these packages to packrat:
            _         
        packrat   0.4.8-20

Not sure whether that has any impact on the project itself though. However it, takes super long.

**Comment by kevinushey** [comment]
Looks like you're using a CRAN mirror that's currently down. You might switch to using the RStudio CRAN mirror (https://cran.rstudio.com).
