### ISSUE TITLE
Why is .git removed from project after packrat::unbundle()?

### ISSUE THREAD

**Issue by hugeme** [rstudio/packrat#424]
Hello,
I'm working with some colleagues on a shared project. We just recently started using packrat. So thx for doing this amazing work.
However, we encountered some issues after `packrat::unbundle()` particularly related to `.git`. 
The workflow we using is pushing the modified repo to github, which inlcudes `packrat::bundle()`. After pushing the newly modified project we pull and  `packrat::unbundle()` , here `.git` is gone and we have to initialize the repo again and setting the remote origin. I'm not sure whether we are doing it wrong or this is a intended behavior.
Appreciate any insights!

**Comment by kevinushey** [comment]
By default, `packrat::bundle()` does discard the Git directory, but you can force it to keep those with:

    packrat::bundle(..., include.vcs.history = TRUE)

**Comment by hugeme** [comment]
@kevinushey thx for your answer. however, Im still struggling to understand the way to handle the workflow with packrat in collaboration with some additional users properly since when you `packrat::unbundle` you have overwrite the existing project.
`Error in packrat::unbundle("/Users/me/packrat/bundles/myproject-2017-11-06.tar.gz",  : 
  Path '/Users/me/myproject' already exists!` perhaps one could add some more information to the README on how to use packrat with git/github in collaboration.

**Comment by kevinushey** [comment]
Generally, you don't use bundle() / unbundle() for sharing the project. Rather, you should just have the project living in a Git repository (e.g. on GitHub), where the Packrat lockfile is synchronized. When collaborators clone the project, they can call `packrat::restore()` to refresh the R library state such that everyone is using the same set of R packages.

Then, normal VCS workflows apply -- make changes, commit them, push them, rinse and repeat.

**Comment by hugeme** [comment]
@kevinushey Thanks alot. Now it makes sense!
