### ISSUE TITLE
Packrat bootstrap fails on 3.4.3 windows with mingw

### ISSUE THREAD

**Issue by WaterworthD** [rstudio/packrat#435]
When I try and open a project after upgrading to 3.4.3 on windows I get the following

```
Packrat is not installed in the local library -- attempting to bootstrap an installation...
> Installing packrat into project private library:
- "C:/dev/r/services/reporting/r/packrat/lib/x86_64-w64-mingw32/3.4.3"
The filename, directory name, or volume label syntax is incorrect.

```

R version 3.4.3 (2017-11-30) -- "Kite-Eating Tree"
Copyright (C) 2017 The R Foundation for Statistical Computing
Platform: x86_64-w64-mingw32/x64 (64-bit)

**Comment by kevinushey** [comment]
I wasn't able to reproduce this on my Windows VM. Any chance you can provide a minimally reproducible example?

**Comment by kevinushey** [comment]
Scratch that -- I was just able to reproduce. I'll take a look and see if I can figure out what's going on.
