### ISSUE TITLE
Use of offline mirror repositories (not CRAN or github)

### ISSUE THREAD

**Issue by schen1** [rstudio/packrat#443]
Hello,

As far as I know, we cannot use mirror repositories with packrat.
Hence, for offline rstudio server or shiny applications, we cannot retrieve the packages if we use packrat.
Is there a way to force packrat to use another offline mirror (e.g. Artifactory or Nexus)?

Thanks.

**Comment by kevinushey** [comment]
I'm not sure what you mean by mirror repository. Packrat works with any kind of CRAN-like repository, both accessible through the internet (through `http://` or `https://`) or local CRAN-like repositories on the filesystem (with `file://`).

**Comment by schen1** [comment]
Thank you for your answer. I am actually talking about a CRAN-like repository using http or https.

FYI I am using https://jfrog.com/knowledge-base/how-to-proxy-a-cran-repo-with-artifactory/ to set up the repository.

How to tell packrat at the initialization of a project to use a specific CRAN-like repository?

Thanks.

**Comment by kevinushey** [comment]
Packrat uses whatever repositories are set in the `repos` R option, so doing something like:

```
options(repos = c(CRAN = "https://my/cran/repo"))
packrat::init()
```

should suffice.

**Comment by schen1** [comment]
Thank you, it is working
