### ISSUE TITLE
auto.snapshot option is not carried over from first "Use packrat with this project"

### ISSUE THREAD

**Issue by ras44** [rstudio/packrat#446]
The first time a user enables packrat with via Tools->Project Options->Packrat by clicking on "Use packrat with this project", the auto.snapshot option selected below is not passed through to the newly initialized project.  By default auto.snapshot is not selected, ie. it should be false.

R installs packrat and runs 
```
packrat::init()
```

And the new project has auto.snapshot=TRUE instead of false as it should be.

**Comment by kevinushey** [comment]
Thanks! This is an RStudio bug; would you mind moving this over to https://github.com/rstudio/rstudio/issues?

**Comment by ras44** [comment]
Thanks!  It is now at https://github.com/rstudio/rstudio/issues/2067
