### ISSUE TITLE
packrat unable to find shared object file for stringi inside docker container

### ISSUE THREAD

**Issue by shapenaji** [rstudio/packrat#455]
Running a packratted shiny app with R within a docker container I get an error about a missing shared library file:

(Not sure if this more relevant to stringi or packrat)

```
packrat::on();library(shiny);shinyAppDir('.', options = list(port = 8000))
Packrat mode on. Using library in directory:
- "/opt/app/packrat/lib"
loading packages - 2018-02-15 17:04:54
Error: package or namespace load failed for ‘tidyverse’ in dyn.load(file, DLLpath = DLLpath, ...):
 unable to load shared object '/opt/app/packrat/lib/x86_64-pc-linux-gnu/3.4.3/stringi/libs/stringi.so':
  libicui18n.so.55: cannot open shared object file: No such file or directory
```

<details>
<summary>libicu-dev is up to date in the container
</summary>

```
root@40050fa01ae5:/opt/app# apt-get install libicu-dev
Reading package lists... Done
Building dependency tree
Reading state information... Done
libicu-dev is already the newest version (57.1-6+deb9u1).
0 upgraded, 0 newly installed, 0 to remove and 4 not upgraded.
```
</details>

<details>
<summary>Dockerfile to reproduce
</summary>

Put dockerfile in the directory of any shiny app that depends on stringi 

```
FROM rocker/tidyverse

# shiny requirements
RUN apt-get update -qq && apt-get install -y \
  git-core \
  libssl-dev \
  libcurl4-gnutls-dev \
  default-jre \
  default-jdk

RUN R CMD javareconf

RUN apt-get install -y r-cran-rjava \
  libproj-dev \
  libgdal-dev \
  unixodbc \
  unixodbc-dev \
  unixodbc-bin \
  libodbc1 \
  odbcinst1debian2 \
  tdsodbc

# mongolite requirements
RUN apt-get install -y libssl-dev \
                       libsasl2-dev

# tidyverse requirements
RUN apt-get install -fy libicu-dev
RUN R -e 'install.packages("devtools")'

# add app data
ADD . /opt/app/
WORKDIR /opt/app/

# initialize packrat
RUN R -e 'install.packages("packrat" , repos="http://cran.us.r-project.org"); packrat::restore(overwrite.dirty=TRUE)'

# start app on port 8000
ENTRYPOINT ["R", "-e", "packrat::on();library(shiny);shinyAppDir('.', options = list(port = 8000))"]
```

and build

```
docker build . --tag shapenaji/reprex
docker run -it shapenaji/reprex
```

</details>

---------
Weirdly,
if I enter the container and install stringi by hand (in the same R session that starts the shiny app) in the packratted directory I can start the app. (But if I do this as part of a previous layer in the dockerfile it does not work. Maybe there's some snapshotting I need to do here as well)

so, for example, this works:
```
ENTRYPOINT ["R", "-e", "packrat::on();install.packages('stringi');library(shiny);shinyAppDir('.', options = list(port = 8000))"]
```

But I would prefer to be agnostic about what packages are being used here beyond making sure that the libraries are available. Also installing as part of the entrypoint adds a lot of startup time.

**Comment by kevinushey** [comment]
In your container, what is the output of:

```bash
ldd /opt/app/packrat/lib/x86_64-pc-linux-gnu/3.4.3/stringi/libs/stringi.so
```

Also, where are the `libicu` libraries installed? Is it possible that a different version of these libraries are installed from what `stringi` is expecting?

**Comment by kevinushey** [comment]
If I'm reading correctly, `libicu-dev` provides version 57.1 of the ICU package:

```
libicu-dev is already the newest version (57.1-6+deb9u1).
```

However, the version of `stringi` installed is looking for an older version (55). Can you just prime the image your container is built from with the required ICU libraries + an installation of `stringi`, or similar?

**Comment by shapenaji** [comment]
I can certainly do that, just install an earlier library. I'm wondering why it gets the right one though when I install stringi directly? it seems like it's holding on to a .so that is invalid
