### ISSUE TITLE
R kernel dead

### ISSUE THREAD

**Issue by spanesar91** [rstudio/packrat#460]
M getting below error:

[I 14:45:56.543 NotebookApp] Accepting one-time-token-authenticated connection from ::1
[I 14:46:06.282 NotebookApp] Kernel started: f66453b9-87d4-4b4d-8112-4a0b5b13a64d
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) : 
namespace 'stringi' 1.1.5 is being loaded, but >= 1.1.6 is required
Calls: :: ... tryCatch -> tryCatchList -> tryCatchOne -> 
Execution halted

can anyone please help

**Comment by kevinushey** [comment]
Sorry, but this is the issues page for the Packrat package; we don't offer general R help here.

The error message is fairly clear:

    namespace 'stringi' 1.1.5 is being loaded, but >= 1.1.6 is required

You need to update the `stringi` package.
