### ISSUE TITLE
error downloading from GitHub on Linux

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#464]
```
Installing yaml (2.1.19) ...
Error in gzfile(path.expand(tarfile), "rb") : cannot open the connection
Calls: <Anonymous> ... local -> eval.parent -> eval -> eval -> eval -> eval
Execution halted
```

Here's the minimal `packrat.lock`:
```
PackratFormat: 1.4
PackratVersion: 0.4.9.1
RVersion: 3.4.3
Repos: CRAN=https://cran.rstudio.com/

Package: yaml
Source: github
Version: 2.1.19
Hash: f81dd406b6ee0951d40ccff6eb03b5c7
GithubRepo: r-yaml
GithubUsername: viking
GithubRef: master
GithubSha1: e004d0bfcb5111a38612e7f6c2939fc387e96c25
RemoteHost: https://api.github.com
RemoteRepo: r-yaml
RemoteUsername: viking
RemoteSha: e004d0bfcb5111a38612e7f6c2939fc387e96c25
```

Here's a script that I have been using to narrow the issue:
```
unlink("packrat/lib", recursive = TRUE)
unlink("packrat/src", recursive = TRUE)
unlink("rlib", recursive = TRUE)

rLibraryDir <- file.path(getwd(), "rlib")
dir.create(rLibraryDir, recursive = TRUE)

.libPaths(rLibraryDir)

install.packages(c("packrat"), 
                 repos = c(CRAN = "https://cran.rstudio.com/"), 
                 lib = rLibraryDir)

packrat::set_opts(
  auto.snapshot = FALSE,
  project = getwd(),
  persist = FALSE
)

packrat::restore(
  overwrite.dirty = TRUE,
  prompt = FALSE,
  restart = FALSE
)
```

That this script succeeds on my macOS host running R 3.4.3 but fails on Ubuntu 14.04 (trusty) also running R 3.4.3.

**Comment by aronatkins** [comment]
This problem did not happen with 4b3e4025404f98d25fb73799e86c1762effe5d7e; it occurred when shifting to f98789177c02b3066144dfb8c39ea67d681fd73c.

**Comment by kevinushey** [comment]
Thanks, I can reproduce with this script. Perplexing because a plain old `packrat::restore()` works just fine. I'll see if I can learn more.

**Comment by kevinushey** [comment]
This was a regression due to https://github.com/rstudio/packrat/pull/448.

Previously, we attempted to use the GitHub downloader only if the necessary machinery was available; if that machinery wasn't available, we fell back to the default R `download.file()` implementation. Unfortunately now we indiscriminately attempt to use the GitHub download machinery and fail to report errors well there.

A workaround is to ensure that the latest CRAN versions of the `httr` and `devtools` packages are installed (alongside their dependencies).

Sorry for the breakage :-/

**Comment by aronatkins** [comment]
Installing `httr` and `devtools` aren't great options in our case, as we were trying to keep the set of vendored dependencies as small as possible (just `packrat` right now).

**Comment by krlmlr** [comment]
Thanks a lot for fixing this, I just hit this problem.

**Comment by alexstoick** [comment]
@kevinushey can you please also push `0.4.9-2` to CRAN?
