### ISSUE TITLE
snapshot unable to retrieve package records for external package

### ISSUE THREAD

**Issue by johnkarlen** [rstudio/packrat#472]
Why does packrat need to find package records when an external package is intended to be used? How do I get around this issue? Do I have to have at least one place where I use all these packages internally?

`
> packrat::set_opts(external.packages = c('teradataR', 'rJava', 'mmlib', 'ggplot2', 'dplyr'))
> packrat::snapshot()
Error: Unable to retrieve package records for the following packages:
  'rJava'
`

**Comment by joelnitta** [comment]
I am having a similar problem, and I think it is because I have a CRAN package that depends on an external package. If `rJava` is a dependency for other CRAN packages, perhaps we are dealing with the same issue. 

If I start a new R project, then save and run the following script, `packrat` has no problems:

```
# Install ape to main R library
# ape is available on CRAN, but I need to download and 
# install the latest dev version from source for my project
download.packages("ape", ".", repos = "http://ape-package.ird.fr/")
install.packages("ape_5.1-3.tar.gz", repos=NULL, type = "source")

# Initialize packrat while ignoring the non-CRAN package
packrat::init(options = list(ignored.packages = "ape", external.packages = "ape"))

# Install a CRAN package with no other dependencies to the packrat library
install.packages("segmented")

# Try to snapshot() - works
packrat::snapshot()
```

However, if I start a new R project and try this, `packrat::snapshot()` errors out with `Error: Unable to retrieve package records for the following packages: - 'ape'`

```
# Install ape to main R library
# ape is available on CRAN, but I need to download and 
# install the latest dev version from source for my project
download.packages("ape", ".", repos = "http://ape-package.ird.fr/")
install.packages("ape_5.1-3.tar.gz", repos=NULL, type = "source")

# Initialize packrat while ignoring the non-CRAN package
packrat::init(options = list(ignored.packages = "ape", external.packages = "ape"))

# Install a CRAN package that depends on ape to the packrat library
install.packages("pegas")

# Try to snapshot()
packrat::snapshot()
```

Here is my `sessionInfo()` before loading anything

```
> sessionInfo()
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: OS X El Capitan 10.11.6

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_3.5.0 tools_3.5.0    yaml_2.1.19   
```

**Comment by johnkarlen** [comment]
solved this by running` packrat::snapshot(infer.dependencies = F)`. Didn't realize snapshot would also try to infer dependencies rather than save just packages specified in init with infer.dependencies = F
