### ISSUE TITLE
Bug in repos_upload()

### ISSUE THREAD

**Issue by mac-pfa** [rstudio/packrat#474]
If an R package under development is build to a .tar.gz file with devtools::build(), and this .tar.gz file is uploaded to a local CRAN-like repos with packrat::repos_upload(), then the .tar.gz file changes file type to a .tar only file, but the name of the file remains .tar.gz.

**Comment by kevinushey** [comment]
Thanks for the bug report! Should be fixed up on master now; I'll be planning a CRAN patch release in the following week.
