### ISSUE TITLE
MXNet installation

### ISSUE THREAD

**Issue by szymonmaszke** [rstudio/packrat#482]
Is it possible to install MXNet using packrat? Automate the installation is some way or should I use shell scripting to do the job? What can packrat do for me here?

Additional question: Is packrat.lock enough to restore the R environment on different machine? Or I have to leave some other files inside ```packrat``` folder? Those can weigh easily in hundreds of mb and I would rather avoid it. 

PS. Sorry if the question is basic, I'm used to Python and pipenv so this tool feels a little strange in comparison.

**Comment by kevinushey** [comment]
Packrat only manages R package installations, so I don't think it would help in the case of MXNet.

`packrat.lock` is indeed the only component required for restoration of the R packages used by a project. Calling `packrat::restore()` will download and install all packages as declared within the lockfile.

**Comment by szymonmaszke** [comment]
I meant MXNet-R package, here are the instructions for the installation: [Installation Instructions](http://mxnet.incubator.apache.org/install/index.html?platform=Linux&language=R&processor=CPU). Leaving aside first three dependencies, would packrat be no help still?

**Comment by kevinushey** [comment]
It looks like the mechanism by which R bindings for MXNet are built deviate from the 'standard' way by which R packages are built, so I don't think Packrat will be able to handle this currently.
