### ISSUE TITLE
Not All Dependencies of ggplot2 Being Tracked/Installed by Packrat

### ISSUE THREAD

**Issue by stephenhmarsh** [rstudio/packrat#484]
I'm trying to install packages via packrat on Debian in a Docker container.  On build, most of my packages succeed, but I am unable to get ggplot2 to finish.

(I do not have this error natively in Mac OSX or Ubuntu where I am initially installing the packages).

Instead, I get the following error message:

```
Error: Command failed (1)

Failed to run system command:

    '/usr/local/lib/R/bin/R' --vanilla CMD INSTALL '/tmp/RtmpfXxahG/tidyverse-ggplot2-79e8b45' --library='/app/lib/groupproject/packrat/lib/x86_64-pc-linux-gnu/3.5.1' --install-tests --no-docs --no-multiarch --no-demo 

The command failed with output:
ERROR: dependencies 'MASS', 'mgcv' are not available for package 'ggplot2'
```

When I look at my `packrat.lock` file, I see no sign of `MASS` or `mgcv`, though they are clearly specified by ggplot2:

```
Imports digest, grid, gtable (>= 0.1.1), lazyeval, MASS, mgcv, plyr (>= 1.7.1), reshape2, rlang, scales (>= 0.5.0), stats, tibble, viridisLite, withr (>= 2.0.0)
```

Here is my packrat.lock file:

```
PackratFormat: 1.4
PackratVersion: 0.4.9.10
RVersion: 3.5.1
Repos: CRAN=https://cloud.r-project.org

Package: BH
Source: CRAN
Version: 1.66.0-1
Hash: 4cc8883584b955ed01f38f68bc03af6d

Package: DBI
Source: CRAN
Version: 1.0.0
Hash: 6abedd7919c4457604c0aa44529a6683

Package: R6
Source: CRAN
Version: 2.2.2
Hash: b2366cd9d2f3851a5704b4e192b985c2

Package: RColorBrewer
Source: CRAN
Version: 1.1-2
Hash: c0d56cd15034f395874c870141870c25

Package: RPostgreSQL
Source: CRAN
Version: 0.6-2
Hash: 3f9effd1b6b265ca9287546537bf5d96
Requires: DBI

Package: Rcpp
Source: CRAN
Version: 0.12.17
Hash: d2eff4634ccd7aca030c540ad805ac4a

Package: Rttf2pt1
Source: CRAN
Version: 1.3.7
Hash: 06f150e8215a48e4f5741ae53eab3947

Package: assertthat
Source: CRAN
Version: 0.2.0
Hash: e8805df54c65ac96d50235c44a82615c

Package: backports
Source: CRAN
Version: 1.1.2
Hash: 5ae7b3466e529e4400951ca18c137e40

Package: bindr
Source: CRAN
Version: 0.1.1
Hash: 76578c5f543a6ecbc1365d6445f9ebf7

Package: bindrcpp
Source: CRAN
Version: 0.2.2
Hash: 557f908819df9f67af5dc93f501610ab
Requires: Rcpp, bindr, plogr

Package: brew
Source: CRAN
Version: 1.0-6
Hash: 931f9972deae0f205e1c78a51f33149b

Package: checkmate
Source: CRAN
Version: 1.8.5
Hash: e1bbc5228ab3da931a099208bc95ad23
Requires: backports

Package: cli
Source: CRAN
Version: 1.0.0
Hash: f4239f89feb7ddc65821e4514e9734ae
Requires: assertthat, crayon

Package: colorspace
Source: CRAN
Version: 1.3-2
Hash: 0bf8618b585fa98eb23414cd3ab95118

Package: commonmark
Source: CRAN
Version: 1.5
Hash: 432a16a9967055dad6b39f1c14fd6b2c

Package: crayon
Source: CRAN
Version: 1.3.4
Hash: ff2840dd9b0d563fc80377a5a45510cd

Package: curl
Source: CRAN
Version: 3.2
Hash: e3318ec2d42d15a38485bab047d114ba

Package: dbplyr
Source: CRAN
Version: 1.2.1
Hash: 167a1e23f4196b09db68b62c99d4f2c2
Requires: DBI, R6, assertthat, dplyr, glue, purrr, rlang, tibble,
    tidyselect

Package: desc
Source: CRAN
Version: 1.2.0
Hash: a1fd2baa29d4954951e3d1816deab6af
Requires: R6, assertthat, crayon, rprojroot

Package: devtools
Source: CRAN
Version: 1.13.6
Hash: 9a137acbaeb61f440b1c1dedc1fbcaec
Requires: digest, git2r, httr, jsonlite, memoise, rstudioapi, whisker,
    withr

Package: dichromat
Source: CRAN
Version: 2.0-0
Hash: 08eed0c80510af29bb15f840ccfe37ce

Package: digest
Source: CRAN
Version: 0.6.15
Hash: 1f202ebd812ac7192be3739245746a13

Package: dplyr
Source: CRAN
Version: 0.7.6
Hash: 8c1063395335450e2fdb82fd9c985b6c
Requires: BH, R6, Rcpp, assertthat, bindrcpp, glue, magrittr,
    pkgconfig, plogr, rlang, tibble, tidyselect

Package: evaluate
Source: CRAN
Version: 0.10.1
Hash: 54d95f4ec6d0300100413ed0127d89ae
Requires: stringr

Package: extrafont
Source: CRAN
Version: 0.17
Hash: d9555d8cfe70b3372d066648400770b5
Requires: Rttf2pt1, extrafontdb

Package: extrafontdb
Source: CRAN
Version: 1.0
Hash: 72269616f582dc675c90ecd025af2754

Package: ggplot2
Source: CRAN
Version: 3.0.0
Hash: 8332448b76ff31472a1bf6dd31fcddb1
Requires: digest, gtable, lazyeval, plyr, reshape2, rlang, scales,
    tibble, viridisLite, withr

Package: ggthemes
Source: CRAN
Version: 3.5.0
Hash: eca97d865f2db311a2697ef77a79ad18
Requires: assertthat, colorspace, ggplot2, scales

Package: git2r
Source: CRAN
Version: 0.22.1
Hash: 2b46fc65cb449ab97c7a38fdcf3ed12c

Package: glue
Source: CRAN
Version: 1.2.0
Hash: 381e42baedecc633c0e547a0c7ca9de7

Package: gtable
Source: CRAN
Version: 0.2.0
Hash: cd78381a9d3fea966ac39bd0daaf5554

Package: highr
Source: CRAN
Version: 0.7
Hash: 20757f5c393ed0ecf96c9e8e6d8d514c

Package: htmlTable
Source: CRAN
Version: 1.12
Hash: 53573f51af4debc4c1ce7ae361d69777
Requires: checkmate, htmltools, htmlwidgets, knitr, magrittr,
    rstudioapi, stringr

Package: htmltools
Source: CRAN
Version: 0.3.6
Hash: b24df7ea0856eab6618f6a56016d940d
Requires: Rcpp, digest

Package: htmlwidgets
Source: CRAN
Version: 1.2
Hash: de18b75f31630089b22e30d4b188cfbe
Requires: htmltools, jsonlite, yaml

Package: httr
Source: CRAN
Version: 1.3.1
Hash: 2d32e01e53d532c812052e27a1021441
Requires: R6, curl, jsonlite, mime, openssl

Package: jsonlite
Source: CRAN
Version: 1.5
Hash: 9c51936d8dd00b2f1d4fe9d10499694c

Package: knitr
Source: CRAN
Version: 1.20
Hash: 9c6b215d1d02b97586c8232e94533e6a
Requires: evaluate, highr, markdown, stringr, yaml

Package: labeling
Source: CRAN
Version: 0.3
Hash: ecf589b42cd284b03a4beb9665482d3e

Package: lazyeval
Source: CRAN
Version: 0.2.1
Hash: 88926ad9c43581fd0822a37c8ed09f05

Package: magrittr
Source: CRAN
Version: 1.5
Hash: bdc4d48c3135e8f3b399536ddf160df4

Package: markdown
Source: CRAN
Version: 0.8
Hash: 045d7c594d503b41f1c28946d076c8aa
Requires: mime

Package: memoise
Source: CRAN
Version: 1.1.0
Hash: 410fcd334bc626db100237cc1370f2e9
Requires: digest

Package: mime
Source: CRAN
Version: 0.5
Hash: 463550cf44fb6f0a2359368f42eebe62

Package: munsell
Source: CRAN
Version: 0.5.0
Hash: 247d1c1d72f3072563912ef860758624
Requires: colorspace

Package: openssl
Source: CRAN
Version: 1.0.1
Hash: e04b8ed7b05c1f75aa81c65a086b1d0c

Package: packrat
Source: github
Version: 0.4.9-10
Hash: 081a95994951a45b273ea12ea46512be
GithubRepo: packrat
GithubUsername: rstudio
GithubRef: master
GithubSha1: 7d320b1c946a5c71232baeba8bc1fa96e9e6befb
RemoteHost: https://api.github.com
RemoteRepo: packrat
RemoteUsername: rstudio
RemoteSha: 7d320b1c946a5c71232baeba8bc1fa96e9e6befb

Package: pillar
Source: CRAN
Version: 1.2.3
Hash: d3b1c0a6cf4b64212509130845c22e09
Requires: cli, crayon, rlang, utf8

Package: pkgconfig
Source: CRAN
Version: 2.0.1
Hash: 0dda4a2654a22b36a715c2b0b6fbacac

Package: plogr
Source: CRAN
Version: 0.2.0
Hash: 81a8008a5e7858552503935f1abe48aa

Package: plyr
Source: CRAN
Version: 1.8.4
Hash: c55fb89c35c97156ff505fc90346110f
Requires: Rcpp

Package: praise
Source: CRAN
Version: 1.0.0
Hash: 77da8f1df873a4b91e5c4a68fe2fb1b6

Package: purrr
Source: CRAN
Version: 0.2.5
Hash: 8b0c16db10c7e20b70cd37779a673a8b
Requires: magrittr, rlang, tibble

Package: reshape2
Source: CRAN
Version: 1.4.3
Hash: 79564c7d36fe3a861158337bc5cc564b
Requires: Rcpp, plyr, stringr

Package: rlang
Source: CRAN
Version: 0.2.1
Hash: 2b163b981be3d6daaac1ad505dd0bf30

Package: roxygen2
Source: CRAN
Version: 6.0.1
Hash: 103c10a2707a21170b74bdde8a5f987a
Requires: R6, Rcpp, brew, commonmark, desc, digest, stringi, stringr,
    xml2

Package: rprojroot
Source: CRAN
Version: 1.3-2
Hash: a25c3f70c166fb3fbabc410eb32b6366
Requires: backports

Package: rstudioapi
Source: CRAN
Version: 0.7
Hash: e2ebaff8160aff3e6b32e6e78a693c2d

Package: scales
Source: CRAN
Version: 0.5.0
Hash: 771a326e90172a053b3e5b9a7add3b13
Requires: R6, RColorBrewer, Rcpp, dichromat, labeling, munsell, plyr,
    viridisLite

Package: stringi
Source: CRAN
Version: 1.2.3
Hash: bccbb90bf5e1c53f659359c06c0dde79

Package: stringr
Source: CRAN
Version: 1.3.1
Hash: 9f417a1d899ed1f080942ab36998e8b5
Requires: glue, magrittr, stringi

Package: testthat
Source: CRAN
Version: 2.0.0
Hash: 537114b476376c5773bf3c557f5bbd19
Requires: R6, cli, crayon, digest, magrittr, praise, rlang, withr

Package: tibble
Source: CRAN
Version: 1.4.2
Hash: 83895360ce4f8d2ce92eee00526b5b0b
Requires: cli, crayon, pillar, rlang

Package: tidyselect
Source: CRAN
Version: 0.2.4
Hash: e489e97d69b6d23822bb34700b45f45b
Requires: Rcpp, glue, purrr, rlang

Package: utf8
Source: CRAN
Version: 1.1.4
Hash: f3f97ce59092abc8ed3fd098a59e236c

Package: viridisLite
Source: CRAN
Version: 0.3.0
Hash: 78bb072c4f9e729a283d4c40ec93f9c6

Package: whisker
Source: CRAN
Version: 0.3-2
Hash: 803d662762e532705c2c066a82d066e7

Package: withr
Source: github
Version: 2.1.2
Hash: dff5b1a8ebb5d03ebf3eec2ad9435a83
GithubRepo: withr
GithubUsername: jimhester
GithubRef: master
GithubSha1: 79d7b0da9f08e853b3195101c09d291f98bba5f3

Package: xml2
Source: CRAN
Version: 1.2.0
Hash: a9af563f148c0170654bd9b4bb974ba7
Requires: Rcpp

Package: yaml
Source: CRAN
Version: 2.1.19
Hash: 6e3d988c25e34c31f668e0ae41dc3259
```

Note for ggplot2, it is missing MASS and mgcv:

```
Package: ggplot2
Source: CRAN
Version: 3.0.0
Hash: 8332448b76ff31472a1bf6dd31fcddb1
Requires: digest, gtable, lazyeval, plyr, reshape2, rlang, scales,
    tibble, viridisLite, withr
```

I am also unable to force Packrat into regenerating a correct packrat.lock by using `remove.packages('ggplot2')` then `install.packages('ggplot2')`

For now I am going to try manually adding MASS and mgcv even though my project does not directly require them.

Edit: PS Here is my packrat.opts:

```
auto.snapshot: TRUE
use.cache: FALSE
print.banner.on.startup: auto
vcs.ignore.lib: TRUE
vcs.ignore.src: TRUE
external.packages: 
local.repos: 
load.external.packages.on.startup: TRUE
ignored.packages: 
ignored.directories:
    data
    inst
quiet.package.installation: TRUE
snapshot.recommended.packages: FALSE
snapshot.fields:
    Imports
    Depends
    LinkingTo
symlink.system.packages: TRUE
```

Edit: PPS - I am more or less using a slightly modified version of [this Dockerfile](https://github.com/rocker-org/rocker-versioned/blob/master/r-ver/3.5.1/Dockerfile)

**Comment by stephenhmarsh** [comment]
Update:

Running `install.packages('MASS')` and `install.packages('mgcv')` also correctly updated the lockfile entry for ggplot2, as well as adding MASS and mgcv as dependencies:

`git diff`:
```
-Requires: digest, gtable, lazyeval, plyr, reshape2, rlang, scales,
-    tibble, viridisLite, withr
+Requires: MASS, digest, gtable, lazyeval, mgcv, plyr, reshape2, rlang,
+    scales, tibble, viridisLite, withr
```

**Comment by kevinushey** [comment]
This is an issue that Packrat has with so-called 'recommended' R packages on Linux. Packrat makes the assumption that 'recommended' packages are available by default on all R installations, as this is true for the most commonly distributed binaries (e.g. on Windows and macOS).

You can see the set of 'recommended' packages with:

```
options(repos = c(CRAN = "https://cran.rstudio.com"))
ap <- available.packages()
ap[ap[, "Priority"] %in% "recommended", ]
```

FWIW the simplest workaround is to just ensure those packages are all installed into the system library.

```
> rownames(ap[ap[, "Priority"] %in% "recommended", ])
 [1] "boot"       "class"      "cluster"    "codetools"  "KernSmooth" "lattice"    "MASS"       "Matrix"     "mgcv"       "nlme"      
[11] "nnet"       "rpart"      "spatial"    "survival"   "foreign"  
```

**Comment by kevinushey** [comment]
There is also the project option `snapshot.recommended.packages` which you can toggle on to ensure that recommended packages always enter the lockfile.

**Comment by stephenhmarsh** [comment]
Thank you, Kevin!!!

Should this be documented somewhere???? Happy to make a PR.

**Comment by stephenhmarsh** [comment]
Also @kevinushey -- sorry dumb question but is there a way to now rebuild my lockfile with this option on so that it checks in these dependences???

**Comment by kevinushey** [comment]
No worries -- no such thing as a dumb question in the context of Packrat :-)

When you say 'rebuild the lockfile', do you mean `packrat::snapshot()`? This is the action that takes the current state of your library paths and serializes them to the lockfile. To restore your library state as encoded in the lockfile, you can use `packrat::restore()`.

**Comment by stephenhmarsh** [comment]
Yeah I was hoping that `snapshot()` would work in such a way that once I set `snapshot.recommended.packages(TRUE)` it would somehow detect those packages missing and rebuild the lockfile with those dependencies specified in it, so I would just then `restore()` to install them.  (I realize this is more like Ruby's Bundler paradigm than how Packrat works, though).

My solution was to just call `install.packages()` with the names of the recommended ones above.   And it works now!! 👍 

Consider this closed if you'd like, thanks again.

**Comment by kevinushey** [comment]
Glad I was able to help!

**Comment by habeeb555-q** [comment]
Getting following errors when I tried to install ggplot2 from rstudio:


In file included from /usr/include/ctype.h:39,
                 from names.c:1:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."
    4 | # error "Never use <bits/endian.h> directly; include <endian.h> instead."
      |   ^~~~~
make: *** [/usr/lib/R/etc/Makeconf:168: names.o] Error 1
ERROR: compilation failed for package ‘vctrs’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/vctrs’
Warning in install.packages :
  installation of package ‘vctrs’ had non-zero exit status
ERROR: dependencies ‘farver’, ‘munsell’ are not available for package ‘scales’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/scales’
Warning in install.packages :
  installation of package ‘scales’ had non-zero exit status
ERROR: dependency ‘callr’ is not available for package ‘pkgbuild’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/pkgbuild’
Warning in install.packages :
  installation of package ‘pkgbuild’ had non-zero exit status
ERROR: dependencies ‘utf8’, ‘vctrs’ are not available for package ‘pillar’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/pillar’
Warning in install.packages :
  installation of package ‘pillar’ had non-zero exit status
ERROR: dependency ‘pkgbuild’ is not available for package ‘pkgload’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/pkgload’
Warning in install.packages :
  installation of package ‘pkgload’ had non-zero exit status
ERROR: dependencies ‘pillar’, ‘vctrs’ are not available for package ‘tibble’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/tibble’
Warning in install.packages :
  installation of package ‘tibble’ had non-zero exit status
ERROR: dependency ‘pkgload’ is not available for package ‘testthat’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/testthat’
Warning in install.packages :
  installation of package ‘testthat’ had non-zero exit status
ERROR: dependency ‘testthat’ is not available for package ‘isoband’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/isoband’
Warning in install.packages :
  installation of package ‘isoband’ had non-zero exit status
ERROR: dependencies ‘isoband’, ‘scales’, ‘tibble’ are not available for package ‘ggplot2’
* removing ‘/home/syed007/R/x86_64-pc-linux-gnu-library/3.6/ggplot2’
Warning in install.packages :
  installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
	‘/tmp/RtmpUDws3M/downloaded_packages’
