### ISSUE TITLE
autoloader check during restore prevents manual libPaths management

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#494]
Given a directory with `packrat/packrat.lock`, the `packrat::restore` call fails because `stopIfNotPackified` stops restoring when an autoloading `.Rprofile` is not detected.

This is a recent change in behavior that landed in https://github.com/rstudio/packrat/commit/f81c5134bab6c4f6d8ab6ecae0b4104e92feba76

**Comment by kevinushey** [comment]
Sorry for the regression -- this should be resolved in #495. Let me know if you're still seeing issues.
