### ISSUE TITLE
RemoteRef not included for GitHub-installed packages

### ISSUE THREAD

**Issue by aronatkins** [rstudio/packrat#502]
Compare the `Github*` fields to the `Remote*` fields; we populate `GithubRef` but not `RemoteRef`.
https://github.com/rstudio/packrat/blob/cea6c235c335b31bd6d3f373ea1e9e29397eff0e/R/pkg.R#L293-L322

**Comment by kevinushey** [comment]
@aronatkins what's the priority on this? In theory you should still be able to grab the ref from `gh_ref` even though we really should populate both fields in all cases.

**Comment by aronatkins** [comment]
I don't think it's high, as folks expect GithubRef, but will want to keep it consistent if we ditch the Github specific prefixes.
