### ISSUE TITLE
Passing R CMD INSTALL Options to packrat::install_local

### ISSUE THREAD

**Issue by hpschrei** [rstudio/packrat#518]
I am trying to install a local package via packrat::install_local and I need to pass the --no-multiarch argument to R CMD INSTALL so that multiple architectures do not get checked. Packrat seems to ignore the options set in Tools/Project Options/Build Tools/Package.

When I run packrat::install_local I can see that the R CMD INSTALL has the following form

R --vanilla CMD INSTALL rPackage \
  --library="C:/Program Files/R/R-3.5.1patched/library" --install-tests 

and that it does not recognize the --no-multiarch flag.

**Comment by cderv** [comment]
`packrat::install_local()` has a `...` argument that is passed through to `packrat::install`. Look at the documentation of `packrat::install`. You can use `args` to pass some options to R CMD  INSTALL, or use an option that gets picked by default `getOption("devtools.install.args")`

So `packrat::install_local(..., args = "--no-multiarch")` should work.

Also, there is a `quick` argument that adds `c("--no-docs", "--no-multiarch", "--no-demo")` as option, so it include what you want. `quick = TRUE` will activate this.
