### ISSUE TITLE
Install packages from github

### ISSUE THREAD

**Issue by mehrnoushmalek** [rstudio/packrat#530]
Hello,

I'm trying to use packrat ( for the first time), but I can't even install devtools, to then install packages from github ( as they are the most up-to-date ones). It gives me an error that libcurl cannot be found. I'm on 16.04 ubuntu, R 3.4.4, and devtools and libcurs are installed in my user library. Is there something that I should add to packrat option to fix this issue?

Thanks in advance, and sorry if it's a duplicate question, but I couldn't find any answer that could help me figure this out.

**Comment by kevinushey** [comment]
You likely need to install the appropriate apt package, e.g.

    sudo apt install libcurl4-openssl-dev

**Comment by mehrnoushmalek** [comment]
But I have devtools installed in my R, I have to do it again?

**Comment by mehrnoushmalek** [comment]
Huh! wouldn't thought it'd work! Thanks Kevin!
