### ISSUE TITLE
packrat::init vs packrat::status

### ISSUE THREAD

**Issue by johanneswaage** [rstudio/packrat#538]
Hi,
In our company, the coding style is to namespace all non-base function calls. We normally don't include library calls in beginning of scripts.
init() does not seem to pick op dependencies from namesspace function calls. status() however, does. Is there any reason for this discrepancy? Could init() also pick up namesspaced calls?

Regards and thanks,
Johannes W

**Comment by kevinushey** [comment]
This should already work in Packrat, e.g.

```r
> packrat:::expressionDependencies(quote({package::routine()}))
[1] "package"
```

Can you provide a reproducible example?

**Comment by johanneswaage** [comment]
Sorry, I can confirm that it works as suggested
