### ISSUE TITLE
UTF-8 non-ASCII characters not handled correctly during restore

### ISSUE THREAD

**Issue by colearendt** [rstudio/packrat#545]
I'm not sure exactly where this would happen, but I have not been able to reproduce it outside of packrat:

This app is a package named "getcolors" which has only one file under the R folder with the following content:

```r
csv='
dsc;color
TELEVISIÓN;#FF0000
RADIO;#6B8E23
'
defcolors=read.csv(text=csv,sep = ";",header = T,stringsAsFactors = F)

getColor=function(dsc){
defcolors[defcolors$dsc==dsc,"color"]
}
```

Never mind the fact that this data could probably be stored in a "better" fashion; is there a reason that installing this package with `install.packages()` works fine, but when installed with `packrat::restore()`, we get:

```r
> dput(getcolors:::defcolors)
structure(list(dsc = c("TELEVISI<c3><93>N", "RADIO"), color = c("#FF0000", 
"#6B8E23")), .Names = c("dsc", "color"), class = "data.frame", row.names = c(NA, 
-2L))
> dput(getcolors:::csv)
"\ndsc;color\nTELEVISIÓN;#FF0000\nRADIO;#6B8E23\n"
```

Note that `defcolors` as a package object incorrectly encodes `TELEVISIÓN` as `TELEVISI<c3><93>N`. There are a handful of workarounds, but it would be good to know why this is happening and see if it is possible to fix. It specifically causes problems for such UTF-8 characters in a package published to RStudio Connect.

Is there an option I am missing?

**Comment by kevinushey** [comment]
This occurs because of this bit of code:

https://github.com/rstudio/packrat/blob/9dee5d88ee41e82382af5acea14107f4eeb8d283/R/install.R#L132-L143

In particular, because we build packages with `LC_ALL=C`, any characters that cannot be represented in the C locale are converted to escapes.

I don't recall the original motivation for that but it may have to do with the fact that R normally runs tests and examples within a C locale for `R CMD check`?

**Comment by colearendt** [comment]
Interesting! And a scary thing to wholesale-change. I don't know that Connect has a way to pass this through today, but would it be possible to have an option or env var or something that overrides this? I think the ideal case would be to override / provide options to a specific package build, because this is clearly a rare scenario (and probably more common in non-English-speaking cultures). If an Env Var (i.e. `LC_ALL_getcolors`), then I would expect it's something Connect could configure / trace through as well. My idea is for the configuration - implementation decisions are way over my head 😆

**Comment by kevinushey** [comment]
https://github.com/r-lib/devtools/issues/507 suggests we could just roll back that use of LC_ALL, at least?

**Comment by colearendt** [comment]
Burn it with 🔥 !!

🙈 🙈 🙈
