### ISSUE TITLE
export fileDependencies?

### ISSUE THREAD

**Issue by AdamSpannbauer** [rstudio/packrat#548]
I know being a dependency finder is not part of the core functionality/use case of `packrat`, but is there any chance of exporting the `fileDependencies()` function?  I am collaborating on a package where using this functionality would be a big help, and we would like to be able to add `packrat` as a dependency to use this capability.

**Comment by kevinushey** [comment]
We're planning to make this available with [renv](https://github.com/rstudio/renv) -- the `renv::dependencies()` function will accomplish this (and will be easier to extend than the Packrat version has been).
