### ISSUE TITLE
Snapshot packages From Github When Installed with `install_git`

### ISSUE THREAD

**Issue by akgold** [rstudio/packrat#554]
Snapshotting with packages installed from public GitHub repos installed by `install_git` fails, but works when installed by `install_github`. Can behavior be changed, or error made more helpful?

Having trouble creating an actual reprex b/c of package installation/packrat...but this failed:
```
remotes::install_git("https://github.com/akgold/gcalendr")
packrat::init()
```

And then this succeeded
```
remotes::install_github("https://github.com/akgold/gcalendr")
packrat::init()
```

**Comment by kevinushey** [comment]
This is because Packrat does not understand how to retrieve packages from general git remotes. This will be implemented in [renv](https://github.com/rstudio/renv).
