### ISSUE TITLE
Gitlab support

### ISSUE THREAD

**Issue by stanstrup** [rstudio/packrat#559]
It seems snapshot will fail if a package comes from gitlab.

```r
Error: Unable to retrieve package records for the following packages:
- "massageR"
```

I guess you don't explicitly support gitlab but is there a workaround?

The following issues about general git support are related:
https://github.com/rstudio/packrat/issues/554
https://github.com/rstudio/packrat/issues/546

**Comment by kevinushey** [comment]
Unfortunately there is no workaround, but support for GitLab will be coming with [renv](https://github.com/rstudio/renv).
