### ISSUE TITLE
Packrat fails to install when gh_subdir is set to character(0)

### ISSUE THREAD

**Issue by alexiswl** [rstudio/packrat#577]
When packrat tries to retrieve it's own source running packrat::on() on an empty directory - after downloading packrat via devtools::install_github it fails.

Reproduced on an empty directory with the following:
devtools::install_github("rstudio/packrat", force=TRUE)
packrat::on()
fails with

Error in if (!file.exists(file.path(basedir, "DESCRIPTION"))) { :
  argument is of length zero

I forked the packrat repo and then debugged by printing the pkgRecord list variable in the function getSourceForPkgRecord

It seems the character(0) is different to 'NULL' and therefore the line:
 if (!is.null(pkgRecord$gh_subdir)) does not return false.
making the test below
if (!file.exists(file.path(basedir, 'DESCRIPTION'))) fail.

After appending identical to the first if to get
if (!is.null(pkgRecord$gh_subdir) && !identical(pkgRecord$gh_subdir, character(0)))
We get to the stage
 ghinfo <- as.data.frame(c(list(
        GithubRepo = pkgRecord$gh_repo,
        GithubUsername = pkgRecord$gh_username,
        GithubRef = pkgRecord$gh_ref,
        GithubSHA1 = pkgRecord$gh_sha1)),
        c(GithubSubdir = pkgRecord$gh_subdir)
      )
Which then fails with:
Error in (function (..., row.names = NULL, check.rows = FALSE, check.names = TRUE,  :
  row names supplied are of the wrong length

**Comment by kevinushey** [comment]
Thanks; I can reproduce. I'll see if I can figure out what's going on.

**Comment by kevinushey** [comment]
Note: most likely unintentional fallout of https://github.com/rstudio/packrat/pull/569.

**Comment by kevinushey** [comment]
This should be fixed up on master now. Thanks for reporting!
