### ISSUE TITLE
packrat::restore():  can't install a package on Windows 7

### ISSUE THREAD

**Issue by kalenkovich** [rstudio/packrat#578]
During `packrat::restore()`, a package fails to get installed even though it's been installed with `devtools::install_github()` on the very same machine. The problem happens during the installation of the [`BFDA`](https://github.com/nicebread/BFDA) package. The error message says that `nm.exe` does not recognize `.o` files.

I am on Windows 7 x64, the R version is 3.5.0 (same result on a different machine with 3.5.3), the RTools version is 3.5 and it is added to the path (see the code). 

Does anyone know how I can solve this?

Things that I've tried that didn't help:

1. Add a `binpref` variable with `Sys.setenv(binpref = 'C:/Rtools/mingw_$(WIN)/bin/')`. The error message implies that `RTools` is located successfully so I did not have high hopes for this one.
2. Manually delete `.o` and `.so` files.

Here is the code to reproduce:

```r
# Install packrat and devtools
current.packages <- installed.packages()
if (!'packrat' %in% current.packages ) install.packages('packrat')
if (!'devtools' %in% current.packages) install.packages('devtools')

# Create a new packrate environment
dir.create('tmp')
setwd('tmp')
packrat::init()
# Wait for the R session to restart
install.packages('devtools')
# Set path to include RTools
Sys.setenv(
  PATH = paste(
    "C:\\Rtools\\bin",
    "C:\\RTools\\3.5\\mingw_32\\bin",
    "C:\\RTools\\3.5\\mingw_64\\bin",
    Sys.getenv("PATH"),
    sep = ";"
  )
)
devtools::install_github("nicebread/BFDA", subdir="package")
packrat::snapshot(snapshot.sources = F)

# Copy packart.lock to a new directory
dir.create('restore_test')
dir.create('restore_test/packrat')
file.copy('packrat/packrat.lock', 'restore_test/packrat/packrat.lock', overwrite = T)
setwd('restore_test')

# Restore the packrat environment
packrat::off()
packrat::restore()
```

The last line results in the following error:

```cmd
        "C:/PROGRA~1/R/R-35~1.0/bin/x64/R" --vanilla CMD INSTALL "C:\Users\oshev
tsov\AppData\Local\Temp\RtmpuexeJJ\package" --library="D:/Kalenkovich/the packra
te dance/tmp/restore_test/packrat/lib/x86_64-w64-mingw32/3.5.0" --install-tests
--no-docs --no-multiarch --no-demo

The command failed with output:
* installing *source* package 'BFDA' ...
** libs
C:\RBuildTools\3.5\mingw_64\bin\nm.exe: RcppExports.o: File format not recognize
d
C:\RBuildTools\3.5\mingw_64\bin\nm.exe: minl_functions.o: File format not recogn
ized
C:/RBuildTools/3.5/mingw_64/bin/g++ -shared -s -static-libgcc -o BFDA.dll tmp.de
f RcppExports.o minl_functions.o -LC:/PROGRA~1/R/R-35~1.0/bin/x64 -lR
RcppExports.o: file not recognized: File format not recognized
collect2.exe: error: ld returned 1 exit status
no DLL was created
ERROR: compilation failed for package 'BFDA'
* removing 'D:/Kalenkovich/the packrate dance/tmp/restore_test/packrat/lib/x86_6
4-w64-mingw32/3.5.
```

**Comment by kevinushey** [comment]
I suspect the error is occurring because the BFDA package authors erroneously included compiled object files in their repository:

https://github.com/nicebread/BFDA/tree/master/package/src

The `.o` and `.so` files should be removed. Packrat could probably work around this by ensuring the R process installing the process is invoked with `--preclean`, though.

**Comment by kalenkovich** [comment]
Thank you @kevinushey. I'll remove `.o` and `.so` files in a fork and try again.

**Comment by kalenkovich** [comment]
Removing `.o` and `.so` worked. Thank you again, @kevinushey!

**Comment by kevinushey** [comment]
Great! I'm glad to hear it. Thanks for reporting back.
