### ISSUE TITLE
Unable to retrieve package records for the following packages: - "icon" In addition: Warning message: In FUN(X[[i]], ...) : Package 'icon' not available in repository or locally

### ISSUE THREAD

**Issue by syzdekbr** [rstudio/packrat#582]
I'm trying to deploy an app to shinyapps.io.  I've been able to deploy other apps and I'm able to run this app locally, but I'm getting the above error message.  There's no package called "icon."

**Comment by kevinushey** [comment]
`icon` appears not to be a package available from CRAN. How did you install it?

If it's this package:

https://github.com/ropenscilabs/icon

then you likely need to reinstall with remotes; e.g. `remotes::install_github("ropenscilabs/icon")`.

**Comment by syzdekbr** [comment]
I don't believe I've installed a package called "icon."  I also don't know of any such package.  There's no call involving such package- no library(icon).  Also, when I run the app locally I don't get such an error.  I have been able to deploy this app before, updated several packages, and am now getting the error.

**Comment by syzdekbr** [comment]
Ah, wait, you are correct, it was in an rmarkdown doc I am using with the app.  Sorry and thanks.

**Comment by GinaOlivares** [comment]
I have the same problem with a ROCR, and honestly I have no idea where it came from

Error: Unable to retrieve package records for the following packages:
- 'ROCR'
In addition: Warning message:
In FUN(X[[i]], ...) : Package 'ROCR' not available in repository or locally
Execution halted

I do not remeber installing that package or even using it.
