### ISSUE TITLE
Am I really supposed to commit the .tar.gz archives in packrat.sources?

### ISSUE THREAD

**Issue by cboettig** [rstudio/packrat#59]
My global .gitignore ignores .tar.gz files, a common configuration I think, since git uses it's own compression algorithm committing these as .tar.gz is inefficient anyhow.  As a consequence, calling `git add packrat.sources` doesn't add anything, but doesn't throw any warning or errors either.  (I suppose this could be an easy stumbling block for anyone pasting in from the documentation?)

I don't quite appreciate why packrat needs the whole `packrat.sources` directory in the first place in addition to the `libraries` directory, (particularly as they contain many of the same packages).  Is it possible to design packrat such that it can just install it's sources from github (say, adding a script that grabs the correct packrat hash from github and installs it), rather than having to carry a copy of packrat and all its dependencies around in my git repo?

**Comment by ijlyttle** [comment]
Hi All,

I found this issue and discussion to be very informative. I don't know the right thing to do is to open another issue or simply continue this discussion.

I have been poking around packrat; in one of my experiments, I found that `install.packages("tidyverse")` on my Ubuntu machine resulted in a `src` directory of 39 MB. 

I understand that a motivation for packrat is to have an ironclad insurance policy, as JJ put it. My question is to wonder if this risk could be managed.

For example, in a project, I might have three different sources of packages:

1. CRAN
2. Public GitHub
3. Private CRAN-like repository

In my mind, CRAN is *almost* ironclad; the other two less-so.

Could it be possible to `.gitignore` the source from packages that were installed from CRAN, but commit the source of packages installed from elsewhere? 

Apologies in advance if this has been discussed elsewhere (I had a quick look).

Thanks!
