### ISSUE TITLE
Packrat incorrectly inferring that Seurat package should be restored from Bioconductor

### ISSUE THREAD

**Issue by pcantalupo** [rstudio/packrat#591]
Hello,

The problem is described in the following Github issues for two repositories:
[Seurat issue 2545](https://github.com/satijalab/seurat/issues/2545) and
[rsconnect issue 399](https://github.com/rstudio/rsconnect/issues/399#issuecomment-578846106)

Can packrat be updated to account for this situation? 

Thank you

**Comment by KinSimon96** [comment]
Hello,

I'm having the same problem than yours. Did you figure it out ?

Thanks

**Comment by mattfemia** [comment]
Hey @KinSimon96 

I've been using a work-around of installing/loading a previous version of Seurat (3.1.0) that didn't have the dependency yet. I also haven't checked to see if this was resolved yet though. 

Running this works for me:
`
library(devtools)
library(rsconnect)

options(repos = BiocManager::repositories())
install_url('https://cran.r-project.org/src/contrib/Archive/Seurat/Seurat_3.1.0.tar.gz')
install_url('https://cran.r-project.org/src/contrib/Archive/SDMTools/SDMTools_1.1-221.2.tar.gz')

deployApp()
`

-Matt

**Comment by pcantalupo** [comment]
Hi ... I did not figure it out. I eventually gave up on Packrat as it was too cumbersome to implement in my workflows.  Good luck.

**Comment by KinSimon96** [comment]
Hey @pcantalupo @mattfemia ,

Thank you for your fast reply! Installing previous version of Seurat seems a good alternative, but won't work for my app: it allows users to subset their own data either for quality control than for deeper cluster analysis. Unfortunately, the 3.1.0 does not recognize inputs in a enclosed environement
`(i.e pbmc <- subset(pbmc, subset = input$gene > 1)`.
This has been corrected by sending them a report but only for the 3.1.5 version... 

Really don't know what to do, i've spent hundreds of hours on it, i hope it will get fixed soon. 

Have a nice day!

**Comment by YTLogos** [comment]
SO the package genetics is the same situation when run rsconnect::appDependencies()

**Comment by KinSimon96** [comment]
I've finally solved it by installing the dev version of Seurat, which corrects dependencies.

**Comment by aronatkins** [comment]
Seurat no longer indicates `biocViews` in its DESCRIPTION.
https://github.com/satijalab/seurat/commit/1592346e83bef247c41a5f1d1ad698a56e8be38b
