### ISSUE TITLE
packrat adds packrat/lib* to .gitignore

### ISSUE THREAD

**Issue by ras44** [rstudio/packrat#593]
I noticed that packrat adds `packrat/lib*` to .gitignore.  Is there a way to turn this off?  While including compiled libs isn't recommended, we often do so because we have a tightly controlled instance model and benefit from not having to reinstall all libs when sharing projects.  Thank you.

**Comment by kevinushey** [comment]
We do. Please see the `packrat::opts$vcs.ignore.lib()` option, documented in `?packrat::opts`.

**Comment by ras44** [comment]
Nice- I swear I looked through that before posting this issue.  Thanks for your help.
