### ISSUE TITLE
How to incremental unbundle ?

### ISSUE THREAD

**Issue by kaji331** [rstudio/packrat#594]
When I have a snapshot with many packages, the unbundle progress is a disaster. Even I just install one package, I have to re-compile all packages when I release a new version script.

Can packrat incremental unbundle?

**Comment by kevinushey** [comment]
No, incremental unbundles aren't possible.

You might want to check out [renv](https://github.com/rstudio/renv) instead -- it uses a global package cache by default, which means restores are usually painless after the cache has been populated.
