### ISSUE TITLE
When I tried to install ggplot2 from rstudio getting so many errors

### ISSUE THREAD

**Issue by habeeb555-q** [rstudio/packrat#601]
### Getting following errors when I tried to install `> install.packages("ggplot2")` from rstudio console although I got message that rstudio is installing so many dependencies

`Installing package into ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6’
(as ‘lib’ is unspecified)
also installing the dependencies ‘ps’, ‘processx’, ‘callr’, ‘prettyunits’, ‘backports’, ‘desc’, ‘pkgbuild’, ‘rprojroot’, ‘rstudioapi’, ‘evaluate’, ‘pkgload’, ‘praise’, ‘colorspace’, ‘assertthat’, ‘utf8’, ‘Rcpp’, ‘testthat’, ‘farver’, ‘labeling’, ‘munsell’, ‘R6’, ‘RColorBrewer’, ‘viridisLite’, ‘lifecycle’, ‘cli’, ‘crayon’, ‘ellipsis’, ‘fansi’, ‘magrittr’, ‘pillar’, ‘pkgconfig’, ‘vctrs’, ‘digest’, ‘glue’, ‘gtable’, ‘isoband’, ‘rlang’, ‘scales’, ‘tibble’, ‘withr’`

**The error message is as follows**

`In file included from /usr/include/ctype.h:39,
from names.c:1:
/usr/local/include/x86_64-linux-gnu/bits/endian.h:4:3: error: #error "Never use <bits/endian.h> directly; include <endian.h> instead."
4 | # error "Never use <bits/endian.h> directly; include <endian.h> instead."
| ^~~~~
make: *** [/usr/lib/R/etc/Makeconf:168: names.o] Error 1
ERROR: compilation failed for package ‘vctrs’`

    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/vctrs’
    Warning in install.packages :
    installation of package ‘vctrs’ had non-zero exit status
    ERROR: dependencies ‘farver’, ‘munsell’ are not available for package ‘scales’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/scales’
    Warning in install.packages :
    installation of package ‘scales’ had non-zero exit status
    ERROR: dependency ‘callr’ is not available for package ‘pkgbuild’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pkgbuild’
    Warning in install.packages :
    installation of package ‘pkgbuild’ had non-zero exit status
    ERROR: dependencies ‘utf8’, ‘vctrs’ are not available for package ‘pillar’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pillar’
    Warning in install.packages :
    installation of package ‘pillar’ had non-zero exit status
    ERROR: dependency ‘pkgbuild’ is not available for package ‘pkgload’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/pkgload’
    Warning in install.packages :
    installation of package ‘pkgload’ had non-zero exit status
    ERROR: dependencies ‘pillar’, ‘vctrs’ are not available for package ‘tibble’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/tibble’
    Warning in install.packages :
    installation of package ‘tibble’ had non-zero exit status
    ERROR: dependency ‘pkgload’ is not available for package ‘testthat’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/testthat’
    Warning in install.packages :
    installation of package ‘testthat’ had non-zero exit status
    ERROR: dependency ‘testthat’ is not available for package ‘isoband’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/isoband’
    Warning in install.packages :
    installation of package ‘isoband’ had non-zero exit status
    ERROR: dependencies ‘isoband’, ‘scales’, ‘tibble’ are not available for package ‘ggplot2’
    removing ‘/home/user01/R/x86_64-pc-linux-gnu-library/3.6/ggplot2’
    Warning in install.packages :
    installation of package ‘ggplot2’ had non-zero exit status

The downloaded source packages are in
‘/tmp/RtmpUDws3M/downloaded_packages’`

**Comment by habeeb555-q** [comment]
This is not a packrat issue in fact this is another package installation error.

**Comment by NikhilNautiyal** [comment]
got the solution??

**Comment by habeeb555-q** [comment]
yes got the solution on that day itself and then got COVID too. Now recovered from dreadful disease but do not remember how I got the solution. For that, I apologize to you.
