### ISSUE TITLE
Bug: error if requireNamespace is used in function

### ISSUE THREAD

**Issue by lz100** [rstudio/packrat#602]
I am been redirected from the rsconnect [issue](https://github.com/rstudio/rsconnect/issues/423) to here. 

First, if I have code like this in my function, packrat treat the variable `pkg` as a real package name. 
```r
missing_pkgs <- lapply(packages, function(pkg) {
        if (!requireNamespace(pkg, quietly = TRUE)) pkg
})
```
Second, this code is used for checking the user environment, I don't want to install or attach the package, so that's why I use `requireNamespace` instead of `require`. packrat also thinks anything in `requireNamespace`  is needed, but they are not.

if you run `packrat:::appDependencies()`:
```r
Warning message:
In FUN(X[[i]], ...) : Package 'pkg' not available in repository or locally
```
This is a warning here, but will become an error in rsconnect and prevent my deployment. 

Is there an official way to fix this instead of my hack? 

Thanks!

**Comment by aronatkins** [comment]
```
> packrat:::fileDependencies.R("app.R")
[1] "shiny" "pkg"  
```

The lower-level logic for handling an expression:
https://github.com/rstudio/packrat/blob/84cbc96726a380dfbdf601535695554241b2acb6/R/dependencies.R#L400-L464
