### ISSUE TITLE
Non-ASCII character prevents packrat from parsing file

### ISSUE THREAD

**Issue by pyltime** [rstudio/packrat#604]
Reported by a RStudio Connect customer in tickets 48151 and 48654 - they had a non-ASCII character in one of the column headers in one of the files that they were trying to deploy to Connect, which caused packrat to fail with the error:

> Failed to parse C:/Users/XXX/AppData/Local/Temp/RtmpyQQrKX/file1b8459f61c6d/app.R ; dependencies in this file will not be discovered.

which in turn, meant that the deployed app failed to run as packages were not installed. 

See the noted tickets in the RStudio Support site for more information, logs, etc

**Comment by vituri** [comment]
Is this related?

https://community.rstudio.com/t/cant-deploy-app-on-shinyapps-when-package-has-special-characters-accent-on-column-names-or-variables-without-backticks/122432

**Comment by aronatkins** [comment]
We believe that this is resolved with https://github.com/rstudio/packrat/pull/647. Please re-open this issue if you are still encountering problems.
