### ISSUE TITLE
Releasing a new packrat version on CRAN?

### ISSUE THREAD

**Issue by slodge** [rstudio/packrat#611]
We're finding the version of packrat on CRAN is causing problems for us - especially with it not correctly picking up our internal CRAN repositories (it lists packages from them as CRAN and warns "Packrat will assume this package is available from a CRAN-like repository during future restores")

I think our issue was solved by https://github.com/rstudio/packrat/commit/da6465073cb05e406183f4e6099e45698daf7e88#diff-248d140618b0a0963077f113fa13f3b8 

To work around this we are getting users to install packrat from github... (but they have to be careful to do this outside any current renv scope...)... It would require less explanation to get our users to install/update from CRAN.

Sorry for asking on this - I realise this is a "cosmetic" rather than functional issue and that development has now moved to renv - however, we're trying to present RStudio and RStudio Connect as a working product set and having to install patches from github feels a bit clunky. It's nice when products work together "out of the box" if you know what I mean (y)

**Comment by kevinushey** [comment]
I think we can try to release a new version of Packrat soon. (Packrat updates are a bit challenging because the jetpack package, which depends on Packrat, always fails its tests when Packrat is updated... and so this requires some conversations with CRAN to fix)

**Comment by slodge** [comment]
Thanks.

If it's a time consuming job, then don't worry too much - I wouldn't want
to steal time away from renv  :)

**Comment by kcarnold** [comment]
This would also help `learnr`. Currently the main README [recommends installing the github version](https://github.com/rstudio/learnr#error-deployment-dependencies-not-found).

**Comment by kevinushey** [comment]
Packrat 0.6.0 is now (finally!) on CRAN. Yay!

**Comment by slodge** [comment]
Thanks!
