### ISSUE TITLE
Cannot snapshot(), DESCRIPTION does not exist

### ISSUE THREAD

**Issue by JimShady** [rstudio/packrat#617]
Not sure why I cannot run snaphot anymore. Any ideas please? Thanks.

![image](https://user-images.githubusercontent.com/2901470/104197876-734ad180-541d-11eb-9115-17c77d8f8f1b.png)

**Comment by JimShady** [comment]
Hmmm. I think it's because renv is searching for the explicit dependencies of a package, but for a specific package it isn't finding a DESCRIPTION? Any method to easily identify which package is causing the problem other than trial and error?

**Comment by kevinushey** [comment]
Did you intend to file this at https://github.com/rstudio/renv/issues?

It looks like you've enabled explicit snapshots but haven't created a project DESCRIPTION file. See `?renv::snapshot` for more information.

**Comment by kevinushey** [comment]
Closing this here but feel free to re-file in the appropriate repository if you're still having trouble.

**Comment by JimShady** [comment]
Apologies @kevinushey . Too many tabs open. Thank you.
