### ISSUE TITLE
packrat trying to install packages from CRAN while it's from Github

### ISSUE THREAD

**Issue by oude-gao** [rstudio/packrat#622]
Hi I am trying to deploy some content depending on an internal package on Github, but packrat tried to install it from CRAN:

[Connect] 2021/02/11 21:13:41.029774085 Installing utlbia (0.0.1.0031) ... 
[Connect] 2021/02/11 21:13:41.136226299 curl: HTTP 200 https://cran.rstudio.com/src/contrib/PACKAGES.rds
[Connect] 2021/02/11 21:13:41.894970372 curl: HTTP 404 https://cran.rstudio.com/src/contrib/Archive/utlbia/utlbia_0.0.1.0031.tar.gz

The DESCRIPTION file looks like this: 

Package: utlbia
...
License: GPL-3
Encoding: UTF-8
LazyData: true
Roxygen: list(markdown = TRUE)
RoxygenNote: 7.1.1
Depends: R (>= 2.10)
Imports: odbc, shiny, dplyr
RemoteType: github
RemoteHost: api.github.com
RemoteRepo: utlbia
RemoteUsername: vnsny-bia
RemoteRef: dev_datasci
RemoteSha: 0a4eaf5764b0028e8775565886e9f3b0af7c8858
GithubRepo: utlbia
GithubUsername: vnsny-bia
GithubRef: dev_datasci
GithubSHA1: 0a4eaf5764b0028e8775565886e9f3b0af7c8858
NeedsCompilation: no
Packaged: 2021-02-11 20:34:00 UTC; root
Built: R 4.0.3; ; 2021-02-11 20:34:01 UTC; unix

The most recent packrat is installed: 
[Connect] 2021/02/11 21:13:40.091572456 Managed packrat version: 0.5.0.26

I would really appreciate it if some solution could be provided. Thanks!

**Comment by scubastevew** [comment]
Hi Oude,

Can you please submit a support ticket here: https://support.rstudio.com/hc/en-us/requests/new

When submitting the ticket, can you also let us know how the internal package was installed from the publishing IDE? 

Can you also can turn on verbose logging in RStudio Server Pro, by going to Tools -> Global Options -> Publishing and selecting "Show diagnostic information when publishing" and sending us the deployment log? 

And finally, can we please get a server diagnostic report from your RStudio Connect server by running this command: `sudo /opt/rstudio-connect/scripts/run-diagnostics.sh /path/to/output/directory`

Attach the server diagnostics report to the support ticket (the output of the script will give you the location of that file).

Thanks, 
Steve

**Comment by oude-gao** [comment]
Thanks! Already did!
