### ISSUE TITLE
Error: Rstudio Server: The previous R session was abnormally terminated due to an unexpected crash.

### ISSUE THREAD

**Issue by GriffyGe** [rstudio/packrat#728]
Detail for my computer(Elastic Computer Service provided by Aliyun): **Ubuntu 22.04 64, 24vCPU, 48Gib**
I am trying to extract sub sequence from a fastq file whose size is **6G** using **Rstudio Server**.
The problem was that when I was running for loop using Rstudio server, I got **"The previous R session abnormally terminated."**  repeatedly. 
I guess the problem was caused as a result of using **`mclapply()`** uncorrectly. Since my computer has 24 cores, I have tried using 10, 12 and 16 cores to run. But all of these situations end up with the error "The previous R session abnormally terminated."
I don't know how to fix this? QAQ

**Comment by aronatkins** [comment]
Without some additional information, it's really hard to say what might be going on.

Would you mind filing an RStudio issue once you are able to explain how to recreate this problem?
https://github.com/rstudio/rstudio
