### ISSUE TITLE
Recursive symlinks in packrat after running tests

### ISSUE THREAD

**Issue by jmcphers** [rstudio/packrat#92]
Repro
1. Build packrat
2. Run tests with `testthat`
3. Build again

Result

```
Warning in file.copy("tests", instdir, recursive = TRUE) :
  problem copying ./tests/testthat/packrat/lib-R/base/base/base/base/base/base/base/base/base/base/base to /Library/Frameworks/R.framework/Versions/3.1/Resources/library/packrat/tests/testthat/packrat/lib-R/base/base/base/base/base/base/base/base/base/base/base: Too many levels of symbolic links
```

**Comment by Brrrknee** [comment]
I am seeing this in my Rstudio environment (March 20 2015) newly installed past 3 weeks, reinstalled yesterday.  packrat is by default enabled per project directory, so RStuio creates the packrat root directory in each project folder.  within that the recursing structure is being recursively created, eating up the filesystem and the cpu; have to task-manager-kill the Rstudio to break out.
packrat is being pulled from wherever Rstudio is getting it, I trust it is a valid package.
The folder being recursed changes depending upon where it spins off the map: I've seen **boot, base, and many others.**  I can paste a few here if needed, but it is clearly this same issue.
**any suggestions? Can i run Git via Rstudio w/o packrat?**  (that's what I am doing now... but haven't had to yet do any Git interaction)

**Comment by vjd** [comment]
I seem to have a similar issue as above - this was not a problem before. It is definitely a packrat issue as I was able to run the code both in R studio without packrat dependency and also in a standalone R session. I am using packrat_0.4.3. Here is my error message 

23 Jun 2015 08:32:52 [rsession-Vijay] ERROR system error 1921 (The name of the file cannot be resolved by the system) 

[path=C:/Users/vjd/Documents/Research/UMB/Contract/rbp/working/analysis/ctm-rbp/packrat/lib-R/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet/nnet]; OCCURRED AT: bool rstudio::core::FilePath::exists() const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:308; LOGGED FROM: bool rstudio::core::FilePath::exists() const C:\Users\Administrator\rstudio\src\cpp\core\FilePath.cpp:308
